### PR TITLE
content(cms): update Person "marcussen-eleonor"

### PR DESCRIPTION
**Pull request by ellisnilsson**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
@ellisnilsson - did you intend to close this pull request?

**Comment by ellisnilsson** [comment]
Hi @VickyGarnett ! I updated, saved, and then set to "in review". That is all.

**Comment by ellisnilsson** [comment]
@VickyGarnett No, I am not sure who is closing my pull requests! It's not me.

**Comment by VickyGarnett** [comment]
@stefanprobst - As you will see above, we have an issue where Sara's pull requests are being closed before I have chance to create a preview and take a look at them.  This seems to only be happening for 'People' rather than for 'Resources'.  Is there a reason you can think of why this is happening?  Thanks :O)

**Pull request closed without merging**
