### PR TITLE
content(cms): create Resource "visual-data-discovery-for-the-social-sciences-and-humanities-context/index"

### PR DESCRIPTION
**Pull request by LottieProvost**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
@ttasovac could you see if there is something preventing the preview link from generating?  Thanks :)

**Comment by ttasovac** [comment]
@stefanprobst when trying to preview this PR, we're getting this: 

```
error - ./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[3].oneOf[6].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[3].oneOf[6].use[2]!./src/styles/globals.css
SyntaxError

<css input> The `text-neutral-900` class does not exist, but `text-neutral-150` does. If you're sure that `text-neutral-900` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[3].oneOf[6].use[1]!/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[3].oneOf[6].use[2]!/Users/ttasovac/Development/DARIAH/dariah-campus/src/styles/globals.css': No serializer registered for SyntaxError
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> SyntaxError
```

I'm not sure how to fix it. Could you please take a look? The weird thing is that this is happening in a PR that was created by the CMS so I don't know why we're having Tailwind issues. 

Many thanks in advance!

**Comment by VickyGarnett** [comment]
Hi Lottie - I'm working to edit this pull request so that it can be published.  However, could you please ensure that all authors have images attached to them.  You can edit an author's 'profile' in the CMS by searching for them under 'People', and then clicking on their name.  This will then bring you through to the person editor form, and you can add images to their profile there.  Images should be in square 1:1 crop, and in either .png or .jpg format.  Thanks :) - V

**Comment by LottieProvost** [comment]
Hi Vicky,

thanks for your email. I didn't know about the photos, sorry ! I will try
and fix it by the end of next week.

All the best,

Lottie

Le mar. 15 févr. 2022 à 15:57, VickyGarnett ***@***.***> a
écrit :

**Comment by VickyGarnett** [comment]
Hi @stefanprobst @ttasovac did the preview issue get sorted?  Thanks :)

**Pull request merged**
