### PR TITLE
content(cms): create Resource "data-and-databases-entities-and-relationships/index"

### PR DESCRIPTION
**Pull request by emilykateemilykate**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate  - I think this one needs a bit of attention.  There needs to be a much more substantial introduction of contextualising few paragraphs for the beginning of the 'Attributes' and 'Associations' sections.  To be honest, it all reads as gobbeldygook to me (sorry!) - a bit like I skipped a lecture and I'm reading someone else's notes on it without any other context.  This needs to be a stand alone module, so if learners need additional information to help them to understand this, you need to add it here.  If that information is covered in one of the other 'database' modules then you should maybe think about merging them so the learner has all the information they need in one place :)

I've made a couple of amendments to the first section that should come through soon, but ultimately I think this needs more work anyway.

Also, there are a few typos throughout that you should pay attention to.  For the most part these seem to be where you missed adding a 'space', but it's not entirely clear to me if that was intentional or not given that some other words seem to combine two words in any case!

V

**Comment by emilykateemilykate** [comment]
Thank you for the feedback!! I'm going to see how it works within the other
modules and perhaps you're right and it makes sense to combine it
with another.  I'll take a look!!

Thank you again,
Em

**Comment by emilykateemilykate** [comment]
I totally reworked it! I hope you like it! I think it stands on its own now and reads less like notes and more like a proper resource. Let me know if you think so too!

**Comment by VickyGarnett** [comment]
THIS IS PERFECT!!!  Thanks for amending all this.  I'll publish it now (after I've updated the publication date) :)

**Comment by emilykateemilykate** [comment]
I’m so happy!!!!!!! Thank you!!!

**Comment by emilykateemilykate** [comment]
It looks amazing live!! How exciting! If you have any suggestions- I’m at
your disposal for the
Prosopography resources in the same way!

**Comment by emilykateemilykate** [comment]
Just circling back to confirm that the other data and databases resources
are good to be published and set into a curriculum? I saw some were
"approved" earlier in the week and I know they have to be published as
individual resources in order to be combined into a curriculum, right? If
they need any edits, I'm happy to do them today!

**Pull request merged**
