### PR TITLE
content(cms): create Resource "an-introduction-to-prosopography/index"

### PR DESCRIPTION
**Pull request by emilykateemilykate**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by emilykateemilykate** [comment]
I see this one will be published soon as its in preview! So exciting! Just let me know about the remaining data and databases ones and we're all done with, I believe!  :) love how theyre all coming together!! Thank you so much!!

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - Thanks for working on this - I'm sorry we didn't manage to get it published before your meeting, but it's not far off now.

The only change I would suggest there is that you remove the header "How do you handle people who may be literary devices?" as this is repeated in the very next sentence, and it already fits in quite well with the heading of the wider section.  So I feel it's a little redundant.

Other than that, I think this is good to go.  Let me know when you've made this change and then I'll add it to the rotation for publication!

V

**Comment by emilykateemilykate** [comment]
Changed it and saved it!

Thank you so much!!!!

**Comment by VickyGarnett** [comment]
@emilykateemilykate  Hooray!  Perfect, I'll add this to the waiting list for publication now, it should be up in a few days !

**Comment by emilykateemilykate** [comment]
Superb!

**Comment by VickyGarnett** [comment]
@emilykateemilykate Actually, just a quick question - the full title of the resource is 'An Introduction to Prosopography', right?  It's just in the preview it's showing up as just 'prosopography' on the abstract card.  I can change that just before I publish, I just want to be sure - cheers :)

**Comment by emilykateemilykate** [comment]
Yes! An introduction to prosopography!

**Pull request merged**
