### PR TITLE
content(cms): create Resource "why-space-is-special-an-intro-to-gis-and-geospatial-history/index"

### PR DESCRIPTION
**Pull request by emilykateemilykate**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - quick Q but what this one written by your colleague?  If so, we should add him as an author.  Could you send me over his details so I can add him to the system and then add him here.  Ta!

Also, could you copy and paste the title into the 'Short Title' field, because for some reason this has no title on the preview.  Ta :)

**Comment by emilykateemilykate** [comment]
Added his name which we had added earlier in the year! Also added short title and put to "now" for publishing! :)

**Comment by VickyGarnett** [comment]
@emilykateemilykate - publishing this one now!  Delighted to have another Pathfinder on the list!

**Comment by emilykateemilykate** [comment]
amazing!!!!!!!!!!!!!!!!!!!

**Pull request merged**
