### PR TITLE
content(cms): create Resource "wikipedia-as-a-source-of-historical-knowledge-applying-digital-source-criticism/index"

### PR DESCRIPTION
**Pull request by spapastamkou**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
@spapastamkou just to let you know I can see this now.  I'll try to get it reviewed within the next week :) - V

**Comment by spapastamkou** [comment]
Thanks, I am glad to know it is now visible to you - sorry for the inconvenience!

**Comment by VickyGarnett** [comment]
Hi @spapastamkou - I've taken a look, and I've made some edits.  You need to go in and add the 'external resource' information.  If you need a reminder for how to do this, you can find it here: https://campus.dariah.eu/docs/using-the-content-management-system#externalresource :)

**Comment by spapastamkou** [comment]
@VickyGarnett I am not sure I managed to do this update, although I added `<Ranke.2>` in the end of content. Why do I not see a separate field for external resource to inform the URL?

**Comment by VickyGarnett** [comment]
Hi @spapastamkou  - if you click on the '+' sign in the format bar (circled in the image below), you will find the 'External Resource' option :)

where is the 'External Resource' option

**Comment by VickyGarnett** [comment]
Hi @spapastamkou - just checking in to see how you're getting on with this.  Have you been able to find the 'External Resource' button?  V

**Comment by spapastamkou** [comment]
@VickyGarnett Done - thanks for your patience!

**Comment by spapastamkou** [comment]
Thank you, Vicky!

**Comment by VickyGarnett** [comment]
@spapastamkou no problem!  Delighted to get this published!  When you get a chance, in a separate branch it would be great if you could add an image to the author's profile

**Pull request merged**
