### PR TITLE
content(cms): create Resource "introduction-to-ai/index"

### PR DESCRIPTION
**Pull request by emilykateemilykate**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi Emily,

A few comments that I hope won't take you too long to fix up:

1. Headings should start at Heading 2 format and work down from there.  This includes your 'Introduction' heading and the 'Learning Outcomes'.
2. I think the sub-sections 'Where to use Prompts' and 'What does an Engineered Prompt Look Like?' are perhaps supposed to go under the 'Introduction to Prompt Engineering in Text-to-Text AI' section?  They certainly would fit better there in any case.  Make sure the headings applied are in line with the other headings around them according to the heading hierarchy.
3. Put 'Example 1...' and 'Example 2...' as headings.
4. You should add a little introductory text under the 'Methods' heading.
5. Where you have 'conclusions', revise these to show that they are a summary of the section (e.g. "Prompt Engineering for Text-based AI In Summary" or something like that).  Leave 'Conclusions' as a heading for the very end of the module.
6. All the sub-section headings after 'Applications of AI' should be stepped down so they sit as sub-headings (I imagine "Applications..." should be Heading 2, and the following headings should be Heading 3 format).
7. Within this 'Applications..." section, I think you should try to group these together a bit more, as it's a very long list, probably with a lot of repetition.  Aim for no more than 7 or 8 groups if you can manage it.
8. The final Conclusion heading should be formatted as Heading 2.

Hopefully this shouldn't be too much work, but I think it'll be nearly ready to go once this is done (unless I spot something else in the meantime!)

Thanks

V

**Comment by emilykateemilykate** [comment]
Absolutely!! I’ll have these done by tomorrow!

Thank you so much,
Emily

**Comment by emilykateemilykate** [comment]
All of the requested changes have been made! Thank you so much.

When you have a chance, please let me know how the others can be polished
for publishing and I'll handle any adjustments right away.

Have a beautiful weekend,
Emily Kate

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - thanks for getting to these changes so quickly!  This is already so much better.

There is still a little bit or re-arranging needed in the first couple of sections.  However, it's a little complicated to explain, and unfortunately I am unable to edit this myself directly.  So instead I've put it all in a Google Doc which I'm going to email over to you now.

Once you've made those changes, could you change the publication date to 'now', and then I think we should be ready to get this published.

Thanks :)

V

**Comment by VickyGarnett** [comment]
@emilykateemilykate  - Another thought: AI is nebulous, so an 'intro to AI' going to be huge.  However, this module focuses on prompt engineering, so I wonder if we should amend the title to reflect that a bit better?  "Introduction to Artificial Intelligence Prompt Engineering" ?  What do you think?

**Comment by emilykateemilykate** [comment]
That’s a great idea! I can reflect that in the title as I make the other
suggested changes!

**Comment by VickyGarnett** [comment]
@emilykateemilykate get excited, I'm about to publish this now!!

**Comment by emilykateemilykate** [comment]
I'm so excited!!!!! Thank you!!!!!!!!!!!!!!!!!!

**Comment by emilykateemilykate** [comment]
The table of contents makes it SO great on desktop! wow!
Thank you so much for your guidance on making this so great!

**Pull request merged**
