### PR TITLE
content(cms): create Resource "looking-for-revolution-in-the-data-pool-some-observations-from-cesta-at-stanford/index"

### PR DESCRIPTION
**Pull request by VickyGarnett**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @ttasovac @stefanprobst I created this yesterday on the CMS, and went through all the steps to publish it, but it seems to have failed.  Nothing during the process suggested there would be any problems, so what did I do wrong? - V

**Comment by ttasovac** [comment]
i sent you an email about this the other day —  check your spam folder if you don't see it in your inbox. a build failed because of some image not being found or something like that. i sent you the error message. let me know if that helps, otherwise, I'll take a look at this tomorrow.

**Comment by VickyGarnett** [comment]
I only created this one last night - the email you sent the other day was about a different PR.  But I'll check the image here again, in case that was the issue here too.  Thanks :)

**Comment by VickyGarnett** [comment]
I removed the image, moved the image to another folder, and re-attached it, and still nothing.  I've also taken the colon out of the title and replaced it with a hyphen, in case that was causing problems, but nope.  So I'm stumped :/

**Comment by ttasovac** [comment]
Did you get the error message I sent you? 
--
Belgrade Center for Digital Humanities
http://humanistika.org

**Comment by VickyGarnett** [comment]
Nothing in the junk mail.  But the email you sent me the other day was for a different pull request, so shouldn't be the issue here?

**Comment by ttasovac** [comment]
it's the same error message on building this resource:
Снимок экрана 2022-03-23 в 18 39 45

if the image for this person is not part of this particular resource, then it can only be fixed locally, in the branch, not through the CMS.  

just mark the resource "for review", don't try to publish it anymore and I will look at it tomorrow. ok?

**Comment by ttasovac** [comment]
in the main branch, the yml file for Iraklis Katsaloulis points to `images/katsaloulis-iraklis.jpeg` but the actual image file is `katsaloulis-iraklis.jpg` not jpeg.  This can be fixed in the main branch by renaming the image file or changing the link in the yml file. after that gets committed and pushed, the should be able to build again... but, as i said, i can do this tomorrow. i'm officially closing the computer now :) have a good evening...

**Comment by ttasovac** [comment]
@VickyGarnett I have fixed the image.

@stefanprobst: I can't preview the main branch locally because of this:

```
./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[3].oneOf[6].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[3].oneOf[6].use[2]!./src/styles/globals.css
SyntaxError

<css input> The `text-neutral-900` class does not exist, but `text-neutral-150` does. If you're sure that `text-neutral-900` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```

both `text-neutral-900` and `bg-neutral-50` in `global.css` are causing this error.  Weirdly enough, I didn't get that error when Vercel built my last commit, but I would still like to get rid of it locally. Could you please help fixing it? 

@VickyGarnett once Stefan confirms that he fixed the remaining error, you should be able to publish your resource.

**Pull request merged**
