### PR TITLE
content(cms): create Event "building-and-linking-humanities-digital-spatial-infrastructures-for-research-in-the-nordic-countries/index"

### PR DESCRIPTION
**Pull request by alexandrapetrulevich**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi Alexandra - have you had a chance to link the video in this resource via YouTube?  Let me know if you have any questions :) - V

**Comment by VickyGarnett** [comment]
Hi Alexandra - So, I've added those videos, which all seem to work perfectly!  But, there is still a little more work to do here I'm afraid.

We need you to add information about the speakers to their profiles on the CMS.  If you go to the preview (You can find this above, but the link is: https://dariah-campus-git-fork-alexandrapetrulevich-cms-a-fdfce9-dariah.vercel.app/resource/events/building-and-linking-humanities-digital-spatial-infrastructures-for-research-in-the-nordic-countries), you will see a grey box for each session that is currently empty.  For this you will need to upload a (square) picture of each speaker and a short biography to their profile.  If you need help doing this, let me know and I can send you some guidance.

I need to work out why I can't get paragraphs in the 'About' section.  Leave that one with me.  

Finally - you'll notice when you click on the preview that when you go to the resource, the on-screen text doesn't really stand out against the background image.  This is a problem for partially sighted and colour-blind people.  So I'll have to make a change to that image (add a gradient) to make it more readable.  This will obscure the image a little, but I wanted to let you know.

Ta!

V

**Comment by VickyGarnett** [comment]
@ttasovac - I seem to have lost the power to deploy previews!  I can go through to the Vercel page where it gives me the option to deploy, but it then comes straight back here rather than going through to the next page to show me the deployment progress.  Are you able to deploy this latest commit from me? - V

**Comment by ttasovac** [comment]
@VickyGarnett the same thing happens to me... i'm in a meeting now but will try to look into it later.

**Comment by ttasovac** [comment]
@VickyGarnett the preview is building now —  it must have been a temporary glitch.

**Comment by VickyGarnett** [comment]
Great thanks Toma!  I'm comforted it wasn't just me :D

**Comment by VickyGarnett** [comment]
@alexandrapetrulevich that's all published now, just waiting for it to build before it gets to the website.  Hopefully it'll be there within the hour.  Thanks for your patience and hard work on this! - V

**Pull request merged**
