### PR TITLE
content(cms): create Resource "mapping-science-in-immersive-architectures/index"

### PR DESCRIPTION
**Pull request by VickyGarnett**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
@stefanprobst @ttasovac Hi both - I merged this yesterday morning for publication, just after I merged PR#599, but neither of them have shown up on Campus yet.  I checked the deployments and they all looked fine.  Is there something I didn't check that would be preventing them both from building properly?  Thx - V :)

**Comment by VickyGarnett** [comment]
> @stefanprobst @ttasovac Hi both - I merged this yesterday morning for publication, just after I merged PR#599, but neither of them have shown up on Campus yet. I checked the deployments and they all looked fine. Is there something I didn't check that would be preventing them both from building properly? Thx - V :)

Hi @ttasovac @stefanprobst Have you had a chance to look at this?  The plan was to have this Friday Frontiers session as tomorrow's Training Tuesday tweet.  Ta :)

**Comment by ttasovac** [comment]
@VickyGarnett @stefanprobst I'm bringing back the conversation here from the email thread, because I found the email thread to be confusing. Let's keep the conversations about particular problems on GitHub so that it's easier to see the background to the particular issue. If a reminder needs to be sent, it should be done in the existing issue or commit on GitHub. 

Stefan, here's a case of a "missing" resource, it's not about the build not completing. Can you please take a look?

**Comment by stefanprobst** [comment]
but isn't the resource missing because the build does not complete successfully, and therefore new new deploy is happening?

Screenshot_20221207_081841

i created a new fork, and deployed from there to vercel, which built and deployed successfully, and it seems to include this resource: https://dariah-campus.vercel.app/resource/posts/mapping-science-in-immersive-architectures

Screenshot_20221207_082018

**Comment by ttasovac** [comment]
so what do we need to do now? can you merge your fork that builds successfully or does that not work when you do it?

**Comment by stefanprobst** [comment]
we need to figure out why it builds when i deploy from my fork, but it does not upstream. maybe some config is different on vercel? not sure yet.

both have the exact same state, i.e. head is at 5bf3d6a, so there is nothing to merge.

**Comment by ttasovac** [comment]
oh, i see. ok, please take a look when you have a moment. if you need to see the Vercel settings, perhaps @VickyGarnett could set up a quick call with you when you both have the time, she is now also a team member on Vercel and has access to everything. thanks a lot in advance, stefan.

**Pull request merged**
