### PR TITLE
content(cms): create Resource "more-watching-less-searching-repurposing-fortunoff-archive-metadata-for-visual-searching/index"

### PR DESCRIPTION
**Pull request by ClaireB82**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by Kfreise** [comment]
Hi Vicky,

Thanks, some comments:

In the abstract text, second sentence first prg, although this is how it's in the blog post, should it not be:

Before this, researchers who were new to Fortunoff’s collection would often find searching *for testimonies* in Yale’s public access catalogue for testimonies an opaque process.

But I am not a native speaker so ignore if you think it doesn't matter.

Under LO, I find the wording 'will be able to understand'' a bit odd, maybe better to say:
search, filter and visualise data found within the Fortunoff archive

Lastly, would it be nice to add links to the Fortunoff Archive?

Thanks!
Katharina

**Comment by Kfreise** [comment]
Sorry, another comment, reading through "Using Named Entity Recognition to Enhance Access to a Museum Catalog" just now I noticed that here, you do name it a training resource although it's an EHRI blog. You don't do this for this one though - I think it's better? Should we consistently refer to them as training resources even though they were first published in our blog?

Thanks.
Katharina

**Comment by VickyGarnett** [comment]
> Sorry, another comment, reading through "Using Named Entity Recognition to Enhance Access to a Museum Catalog" just now I noticed that here, you do name it a training resource although it's an EHRI blog. You don't do this for this one though - I think it's better? Should we consistently refer to them as training resources even though they were first published in our blog?
> 
> Thanks. Katharina

OK - now I see it.  Um, it's up to you.  If you prefer 'training resource' we can go with that, but again if it's your blog and you want to highlight that we can leave it as 'blogpost'.  Which would you rather? - V

**Comment by Kfreise** [comment]
Well, I don't really have a preference, I just noticed that it wasn't consistent, so sometimes we would say blogpost, sometimes (training) resources, even though it always refers to EHRI Blogs. But if you don't think that is an issue I am also happy to leave - it's not a big thing.

**Pull request merged**
