### PR TITLE
content: [acdh-ch] add datenmanagement-uebung

### PR DESCRIPTION
**Pull request by stefanprobst**

### CODE REVIEW

**Comment by VickyGarnett** [comment]
@maria-wie - I'm not getting the Google Chrome translation this time, but it looks like this module just ends rather than finishes.  Could you add a brief concluding paragraph that summarises that was been covered?

Also, we need learning outcomes for this as well.  Thanks :)

**Comment by VickyGarnett** [comment]
@maria-wie - could you add an introductory paragraph to explain what this very short module is about, learning outcome(s) and a concluding paragraph to summarise what was covered.  This resource should stand alone so that people coming to this without any prior knowledge can follow it :)

**Comment by maria-wie** [comment]
this is a practical exercise for the datenmanagement learning resource. it is part of the curricula, but should not stand alone as a resource in dariah-campus. maybe it should be included in the datenmanagement learning resource.

**Comment by VickyGarnett** [comment]
Hmm yeah, maybe including it in a larger module that can stand alone makes more sense :)

**Comment by VickyGarnett** [comment]
If you have others like this you should maybe think about whether they should also be incorporated into another larger module :)

**Comment by maria-wie** [comment]
Closing this in favour of #1246

**Pull request closed without merging**
