### PR TITLE
content(cms): create Resource "encode-course-digital-tools-for-the-research-and-study-of-ancient-writing-cultures/index"

### PR DESCRIPTION
**Pull request by fosco13**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @stefanprobst - this pull request is failing to deploy.  I had a crack at fixing it, but there's a chance I made things worse.  Would you mind taking a look at what the issue is when you have a moment?  Thanks - Vicky :)

**Comment by stefanprobst** [comment]
@VickyGarnett 

building fine for me locally.

can you provide error logs from vercel (i don't have access)?

**Comment by VickyGarnett** [comment]
> @VickyGarnett
> 
> building fine for me locally.
> 
> can you provide error logs from vercel (i don't have access)?


 Hi @stefanprobst  - This is a screengrab of the error messages :). Thanks!

Screenshot 2024-10-07 at 11 56 05

**Comment by VickyGarnett** [comment]
Hi @fosco13 - We have a preview!  Which means I can review this properly now.  There are few things that need to be added, and a few changes, so I'll to be as succinct as possible:

- Add a description of the course to give potential learners a good idea of what is covered
- learning outcomes should be much shorter (try to keep them to 1 line), and perhaps limit it to just 4 learning outcomes max.  Much of what is described in here could probably be covered in the description that goes above.
- remove the 'bold' formatting from the learning outcomes, and the sentence under the heading should be 'After completing this course, learners will be able to:' .  The bullet points should then all follow on from this to complete the sentence
- Add the link out to the resource using the 'External Resource' option (found if you click on the + symbol in the content field)

You can see an example of how this should all look here: https://campus.dariah.eu/resource/posts/creating-guis-in-python-for-digital-humanities-projects (your description doesn't need to be as long as this).

Thanks!

V

**Comment by fosco13** [comment]
Thanks @VickyGarnett! I'll try to modify it later this afternoon and give you a shout as soon as it is done...

**Comment by fosco13** [comment]
> Thanks @VickyGarnett! I'll try to modify it later this afternoon and give you a shout as soon as it is done...

I've noticed you already made the final edits @VickyGarnett, thanks! Only remaining thing I was unsure about was whether the external URL could also remain in the Remote Host (Optional) field? If not, let me know and I can still remove it there (it is added now as external resource directly under the learning outcomes in the description...

**Pull request merged**
