### PR TITLE
content(cms): create Resource "spatial-queries-and-the-first-deportations-from-slovakia/index"

### PR DESCRIPTION
**Pull request by ClaireB82**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by Kfreise** [comment]
Hi,

I worry that Michal wont like the shortening of the first bit, I suggest this:

As part of his EC-funded project Unlikely Refuge ((Link to https://www.unlikely-refuge.eu/)), Michal Frankl examined the deportations of Jews from Slovakia in November 1938, many of whom were subsequently trapped along the demarcation line between the Czecho-Slovak and Hungarian post.

In the last prg, you say "To answer these questions, Michal digitised" but it's 'we' in the original so I suggest saying "Michal and his team". You also have 'This blogpost on the EHRI website outlines", which otherwise I think we never say? Just delete and say ''resource'' instead? And last sentence please  say 'outlines the steps the team took' instead of 'outlines the steps Michal took'.

Otherwise I think it's ok.

Thanks!
Katharina

**Comment by VickyGarnett** [comment]
@Kfreise I've made those updates now - you should be able to see them here: https://dariah-campus-h54gsb64j-dariah.vercel.app/resource/posts/spatial-queries-and-the-first-deportations-from-slovakia

Is this one good to publish?

**Comment by Kfreise** [comment]
Hi,

Sorry, but I  am now unsure about the timing of the research (what did he do when), so maybe do this small edit:

replace: his EC-funded project Unlikely Refuge (https://www.unlikely-refuge.eu/)
with: his research (see EC-funded project Unlikely Refuge https://www.unlikely-refuge.eu/)

Otherwise good to go!
Katharina

**Comment by VickyGarnett** [comment]
> Hi,
> 
> Sorry, but I am now unsure about the timing of the research (what did he do when), so maybe do this small edit:
> 
> replace: his EC-funded project Unlikely Refuge (https://www.unlikely-refuge.eu/) with: his research (see EC-funded project Unlikely Refuge https://www.unlikely-refuge.eu/)
> 
> Otherwise good to go! Katharina

@Kfreise Jolly good.  I've made that change now, and just waiting for the preview to deploy.  If you have no further comments, I'll just push it straight through to publish, and we will have another 2 off the list today!  I have another resource currently in the making, so hopefully we can get 2 more EHRI resources published in the next couple of weeks.  V

**Comment by Kfreise** [comment]
Great, thank you, Vicky. I noticed that only Rachel's resources have her photo and not the others - are there any missing? I thought I had sent them to you but maybe I need to chase.

**Comment by VickyGarnett** [comment]
> Great, thank you, Vicky. I noticed that only Rachel's resources have her photo and not the others - are there any missing? I thought I had sent them to you but maybe I need to chase.

Let me check that.  I had noticed a lot of pictures missing as well, but I assumed it was because we hadn't received them yet.  But if you are seeing people that you think you have already sent me picture for, it may be a problem in the yaml files.  I'll have a look and get back to you in an email.  But that won't prevent us from publishing these in any case.

**Comment by Kfreise** [comment]
Ok, I sent you 6 photos in total so there may well be photos missing.

**Pull request merged**
