### PR TITLE
content(cms): create Event "performing-arts-transitioning-to-the-digital-age/index"

### PR DESCRIPTION
**Pull request by azugic**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @azugic !  Good news, the preview is now available!  You can preview the event here: https://dariah-campus-git-fork-azugic-cms-azugicdariah-ca-d60bf4-dariah.vercel.app/resource/events/performing-arts-transitioning-to-the-digital-age

You will see that some of the speakers have information missing.  I think there is a pull request to update your own profile that I need to take action on, so hopefully that will resolve that.  But some of the other speakers are missing images.

I will also need to make a few minor tweaks to this, such as amending the title so it's not ALL CAPS, and updating the publication date.  I'll also do a quick check to make sure all the links are working properly.  You dan also check these links if you like.

Otherwise, we are very close to publishing.  I'm sorry it's had this delay, but I'm really pleased we can get this one published for you very soon.

Thanks

Vicky

**Comment by VickyGarnett** [comment]
Hi @stefanprobst - I've got another failed Vercel preview after updating the branch :/. Another PR was updating an author that is listed in this PR.  So, I reviewed and merged that PR.  I then hit 'Update Branch' on this PR so that the author info would show up properly, and the Vercel preview then failed.

I've got a screengrab of the fail page on Vercel for you to have a look at.

Thanks!

Vicky

Screenshot 2023-06-22 at 13 43 07

**Comment by VickyGarnett** [comment]
@azugic Hi Anamarja - We've got a preview of this event now, but I see that we are missing a few authors for the last few sessions.  We have 'DARIAH-Campus' in there at the moment and this needs changing.  I'm also still missing an image for Vasiliki.  We're nearly there! - Thanks V

**Comment by azugic** [comment]
Hi Vicky, I'll do my best to fix that as soon as possible.

Anamarija

**Comment by azugic** [comment]
Dear Vicky,

When I originally created this event, I put all the speakers in the
Collection People and sent them for review. After each record was approved,
I inserted each individual person (speaker) into the event with the
appropriate presentation and saved it. I sent the whole event for review
and now what happened is that a certain number of speakers disappeared from
Collection People and that is why I can no longer choose them from the
drop-down menu (PrtScr 1). There also seems to be a bug in that list
(PrtScr 2). Is it possible to fix that or I will have to make new records
of people once again?
Regarding the photo for Vasiliki, we don't have one and probably won't be
able to obtain one, so I'm wondering how much of a problem it is that some
speakers don't have a photo. Can it be published without a photo?
Also, I noticed that the photos are not visible in the preview. Is it just
like that in the preview or is it also some problem that needs to be
solved? (PrtScr 3)

Best
Anamarija

**Comment by VickyGarnett** [comment]
Hi @azugic - I'm really sorry you're having these problems with the system.  I think it's possible we might need to have a chat to iron these problems out so I can make sure I'm not making assumptions or misunderstanding you.  Are you at the DH conference in Graz?  If so, would you have a free coffee break where we can find a quiet corner and go through it?  If not, maybe we should schedule something for next week?  I'd like to make absolutely sure that all the speakers are definitely in the system, and then have a look at why they aren't showing up on the preview.  It's possible, indeed likely I'll need to defer to @stefanprobst  if this isn't a problem I can fix, but we'll cross that bridge if/when we come to it.

**Comment by azugic** [comment]
Dear Vicky,

I am in Zagreb, unfortunately, but we can meet on Zoom any day next week
between 9 am and 2 pm CEST.

**Comment by VickyGarnett** [comment]
Hi @stefanprobst @ttasovac  - Anamarija and I went through the index.mdx for this event just now in a call to make sure everything was as it should be.  There are couple of speakers without images, but they can be dealt with in a separate pull request.  The important thing is that all speakers have a yaml file, and that is linked to from the index.mdx file.

However, I'm still getting errors in the deployment, so something still isn't right.  The image below gives the details from Vercel:

Screenshot 2023-09-11 at 11 02 53


I've looked up what a prerender error is, and it points to possible unnecessary props.  As this Pull Request was made before we fixed the issue in the Triple event, I think it still has the issues from that, and I think we solved that by removing the 'kiraly' file from the Triple event downloads folder because it was redundant.  However, as you can see from the Atom layout, this is still there and showing up orange:

Screenshot 2023-09-11 at 11 02 47

Do I just remove that 'downloads' folder from the Triple event in this pull request, as it's redundant?  Could that be causing the problem?

It'd be great to get this sorted so we can publish this 'Performing Arts' event either today or tomorrow.  Everything else is in place (we just need to add a few images to speakers), so it would be great to get this problem sorted so we can get it out the door.

Thanks!

Vicky

**Comment by stefanprobst** [comment]
fixed yaml frontmatter indentation

**Comment by VickyGarnett** [comment]
@azugic Good news - thanks to @stefanprobst we now have a preview.  You can view it here: 
https://dariah-campus-3x3a3ircw-dariah.vercel.app/resource/events/performing-arts-transitioning-to-the-digital-age

I've noticed a few things to change here, most notably the links to the full event synthesis.  What we currently have it linked to is the call for papers for the event, which isn't a summary of the event at all.  Instead, I propose that this is linked to the Book of Abstracts:
https://dariah.hr/arhiva/Performing-Arts--Transitioning-to-the-Digital-Age--Book-of-Abstracts.pdf
Also, ideally the individual sessions would have links to the slides for each presentation, if you have them.  If not, then we can publish now and the slides can be added at a later date, it just means a change to the version.

If you're happy for me to do so, I can make that change to the 'Full Event Synthesis' document. 

I also think the link out to the event webpage that is used in the first session synthesis can be included in the 'About' information, along with the call for papers.

As discussed, if you can send me over the speaker pictures, I can add them asap.

Finally, would you like all the speakers listed in the 'authors' section to the entire event, or just the organisers?  If it's just the organisers, could you let me know who these people are, and what order you'd like me to put them in (by default I would put them alphabetically by surname) 

So very nearly there!

V

**Comment by VickyGarnett** [comment]
> fixed yaml frontmatter indentation

Thanks Stefan! :D

**Comment by azugic** [comment]
Dear Vicky,

I'm sorry, I need to postpone handling these issues until Monday. Today I'm
traveling to the PUBMET conference in Zadar with Koraljka and things are a
bit chaotic, so I'm not sure if I'll have the time to address everything
you mentioned in your previous email. Rest assured, I'll definitely take
care of everything first thing on Monday.

Best
Anamarija

**Comment by VickyGarnett** [comment]
No problem @azugic just drop me a message when you've had a chance so I get a prompt :)

**Comment by VickyGarnett** [comment]
Hi @azugic - have you had a chance to look at the proposed changes I mentioned above?  Cheers - V

**Comment by azugic** [comment]
Dear Vicky,

So sorry for the prolonged delay in this matter. It seems that my response
to your comments and suggestions got lost when I sent the email with the
photos, which wasn't going through due to the attachment size. Here's what
I had written:

"Dear Vicky,

Sorry for the late reply. I agree with all your comments and suggestions.
Could you please go ahead and make the changes in the event as you
mentioned? I am also sending you photos that I owe you. I managed to obtain
the one that was missing, so there's no need for me to send you the logo.
Btw, Gordan Kreković's photo is now visible on the event page, so I skipped
that one.
Unfortunately, I don't have presentations from all the authors, and I'm not
sure if they would be willing to share them, but most of the PPT content is
visible in the recordings. Will that suffice?"

In any case, you probably already added the photos, and I agree with all
the other suggestions you mentioned. I asked if you could directly input
them. That should be it – I've already checked and confirmed all other
items (texts and attachments in the event).

Best,
Anamarija

**Comment by VickyGarnett** [comment]
Hi @azugic ,

Thanks for this!  I'll crack on with the changes.  However, I don't think I ever received the photos you mentioned. If you can send them on again (direct email to me is fine) that would be great.

As for no presentation slides for the different sessions - that's fine.  It's not ideal, we do like to include them, but it's not a deal-breaker :)

V

**Pull request merged**
