### PR TITLE
content(cms): create Resource "exploratory-topic-modelling-in-python/index"

### PR DESCRIPTION
**Pull request by ClaireB82**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @ClaireB82 - I'm sorry to ask but could you re-work this sentence: "Topic modelling is a technique by which documents within a corpus are clustered based on the manner in which certain groups of terms are used together within the text. "  It's a bit clumsy and has a lot of repetition in it. 

I've made a few edits to this resource to bring it more in line with the house style (e.g. use of headings, the order in which things appear, etc).   I've also made changes to the abstract to make it a bit more of an overview of the resource.

If you could give me some new wording for that opening sentence, that would be really useful, thanks!

V

**Comment by VickyGarnett** [comment]
Hi @ClaireB82  - I've made some edits, but I'm still not sure how to rework that first sentence without potentially losing the intended meaning.

Could you take a look at the preview I've created with my proposed edits, and let me know if you're happy.  If you could also have a think about a different way to rephrase that opening sentence, that would be great.  I can get this one published ASAP then :)

https://dariah-campus-git-fork-claireb82-cms-claireb82dar-2a1fc0-dariah.vercel.app/resource/posts/exploratory-topic-modelling-in-python

Thanks

V

**Comment by Kfreise** [comment]
Hi,

Could you please edit as follows:

- the abstract here seems shorter than the other one on quod, would it be possible to replace the first two sentences in the abstract with the wording from the Blog: Topic modelling is a technique by which documents within a corpus are clustered based on how certain groups of terms are used together within the text. The commonalities between such term groupings tend to form what we would normally call “topics”, providing a way to automatically categorise documents by their structural content, rather than any a priori knowledge system. 
 - could you link to the blog that's now up https://blog.ehri-project.eu/2022/07/19/exploratory-topic-modelling-in-python/? 
 - Outcomes; don't capitalise topic modelling

**Comment by VickyGarnett** [comment]
Hi Katharina - Thanks for looking through this resource.  I've corrected that typo in the learning outcome, and changed the link to the blog post.  I'll replace the first sentence in the abstract with what you have written, but I would want to avoid using Latin terms such as 'a priori' in an abstract, as code-switching can make it a bit less accessible.  So I'll pop in an alternative, if that's OK :) - V

**Pull request merged**
