### PR TITLE
content(cms): create Person "sigurðarson-eiríkur-smári-1"

### PR DESCRIPTION
**Pull request by EirikurSmariSigurdarson**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @EirikurSmariSigurdarson  - I see you've sent in this pull request for a person to be added.  I just want to double-check with my technical colleague about why it ends in "1" as this suggests we already have you on the system, I just can't see you anywhere :). I'll get back to you asap.

Thanks

Vicky

**Comment by VickyGarnett** [comment]
Hi @stefanprobst - This pull request is to add a new person to the CMS.  However, the presence of "-1" at the end indicates to me that they are already in there.  I've checked the yaml files and can't see them there (but then we all know my ability to miss things), but maybe there is another explanation for this.  I want to avoid creating a duplicate.  Thanks :). Vicky

**Comment by EirikurSmariSigurdarson** [comment]
I was just trying to register myself as a person – as I couldn’t find myself in the list. Probably made some mistake in the process.

Best,
Eiríkur Smári


From: VickyGarnett ***@***.***>
Date: Wednesday, 7 February 2024 at 20:03
To: DARIAH-ERIC/dariah-campus ***@***.***>
Cc: Eiríkur Smári Sigurðarson - HI ***@***.***>, Mention ***@***.***>
Subject: Re: [DARIAH-ERIC/dariah-campus] content(cms): create Person "sigurðarson-eiríkur-smári-1" (PR #974)

Hi @stefanprobst<https://github.com/stefanprobst> - This pull request is to add a new person to the CMS. However, the presence of "-1" at the end indicates to me that they are already in there. I've checked the yaml files and can't see them there (but then we all know my ability to miss things), but maybe there is another explanation for this. I want to avoid creating a duplicate. Thanks :). Vicky

**Comment by VickyGarnett** [comment]
Don't worry @EirikurSmariSigurdarson , it's fine - I'm just being cautious!  Hopefully we'll know for definite one way or another tomorrow and I can get this one sorted out for you :)

**Comment by VickyGarnett** [comment]
Hi @EirikurSmariSigurdarson  - I'm sorry it's taken me so long, but I think that name addition has been sorted out now, and I've merged it.  You should be able to find yourself in the CMS within the next 10 mins or so.

Thanks

Vicky

**Comment by EirikurSmariSigurdarson** [comment]
No worries! I have not had time to do anything, but now is time. Best, Eiríkur

Frá: VickyGarnett ***@***.***>
Sent: miðvikudagur, 14. febrúar 2024 17:33
Til: DARIAH-ERIC/dariah-campus ***@***.***>
Afrit: Eiríkur Smári Sigurðarson - HI ***@***.***>; Mention ***@***.***>
Efni: Re: [DARIAH-ERIC/dariah-campus] content(cms): create Person "sigurðarson-eiríkur-smári-1" (PR #974)


Hi @EirikurSmariSigurdarson<https://github.com/EirikurSmariSigurdarson> - I'm sorry it's taken me so long, but I think that name addition has been sorted out now, and I've merged it. You should be able to find yourself in the CMS within the next 10 mins or so.

Thanks

Vicky

-

**Pull request merged**
