### PR TITLE
content(cms): create Resource "using-named-entity-recognition-to-enhance-access-to-a-museum-catalog/index"

### PR DESCRIPTION
**Pull request by ClaireB82**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by Kfreise** [comment]
Hi Vicky,

I wonder here whether the LOs could be slightly rephrased to be more concrete and link better with the standard sentence (i.e., '' users will be able to" doesn't really work with ''learn about the location extraction from text'. 

Should we maybe say:

- Understand how DH tools can help to automatically extract specific information from big data sets
- Explore named-entity recognition in oral history catalogs 

What do you think?

Best,
Katharina

**Comment by VickyGarnett** [comment]
> * Understand how DH tools can help to automatically extract specific information from big data sets
> * Explore named-entity recognition in oral history catalogs

Agreed - and I prefer your phrasing of this :) - V

**Comment by Kfreise** [comment]
Hi,

I noticed that you used the UK spelling in the new LOs, but it's written in US, so maybe change it back to 'catalog' even if it hurts? :)

Katharina

**Comment by VickyGarnett** [comment]
Hahah, well spotted Katharina, I hadn't even realised (I was typing them in and must have been on auto-pilot).  I'll change them to the US spelling if that is what is used in the resource, no problem.

V
________________________________

**Comment by VickyGarnett** [comment]
@Kfreise - updates made now, plus one minor typo corrected.  If you could take one last look, I can publish this one today :)

**Comment by VickyGarnett** [comment]
> @Kfreise - updates made now, plus one minor typo corrected. If you could take one last look, I can publish this one today :)

https://dariah-campus-r8hi0ofom-dariah.vercel.app/resource/posts/using-named-entity-recognition-to-enhance-access-to-a-museum-catalog

**Comment by Kfreise** [comment]
Hi,
Looks good, thanks. What did you decide about using 'blog' or ''training resources''? 
Cheers, 
Katharina

**Comment by VickyGarnett** [comment]
> Hi, Looks good, thanks. What did you decide about using 'blog' or ''training resources''? Cheers, Katharina

Oooh, I don't remember that discussion, sorry.  Can you remind me?

**Comment by Kfreise** [comment]
I said it in another one that I looked at at the same time, sorry about the confusion; https://github.com/DARIAH-ERIC/dariah-campus/pull/608#issuecomment-1491528921

**Comment by VickyGarnett** [comment]
OK grand - have responded in that pull request.  Publishing this now.  Hooray!

**Pull request merged**
