### PR TITLE
chore: updating node version info

### PR DESCRIPTION
**Pull request by VickyGarnett**
Adding notes regarding which version of 'node' is required.

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Just want to make sure I've put the right info in the right place :)  Ta - V

**Comment by stefanprobst** [comment]
i think we should make sure that DC can be built with node version 16 - version 14 is no longer maintained.

**Comment by stefanprobst** [comment]
looks like it is building fine with node v16.17.0 on my machine. can you post an error message you get? if it's building fine for you as well we should suggest using v16

**Comment by stefanprobst** [comment]
(will probably also require bumping the node version configured on vercel)

**Pull request closed without merging**
