### PR TITLE
content(cms): update Resource "ethical-societal-and-legal-complexities-of-ai/index"

### PR DESCRIPTION
**Pull request by emilykateemilykate**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate just confirming that I have seen this PR and as soon as the preview is deployed I'll take a look :)

**Comment by emilykateemilykate** [comment]
Super! Thanks so much!

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - this is definitely closer, but there are still a few things to sort out.  Again, hopefully not too big a list that means you'll be up 'til late!

**Abstract** 
-  replace "Learners should be equipped" with "Learners will be equipped'.  'Should is a bit ambiguous here and could be read that they must have a certain set of skills before they undertake the course.

**Main content**
- In first line immediately following the learning outcomes, introduce the acronym 'AI' here straight after "Artificial Intelligence", as this is the last time you use the full name and from then on you use the acronym.
- Toggle the 'Table of Contents' switch on
- Some of the content still needs a bit of fleshing out as we are left asking more questions from the points you raise.  For example: in Ethical Issues under 'Potential Risks', there is "Artificial Intelligence in Warfare: The use of Artificial Intelligence in military applications, such as autonomous weapons, raises ethical concerns about the potential for indiscriminate harm and the erosion of human responsibility in warfare."  A bit more info about the ethical concerns here would be useful.  

Equally, "Artificial Intelligence and Education: The role of Artificial Intelligence in education and the potential impact on the workforce and learning outcomes were subjects of debate."  A debate between whom?  What were the arguments?  These aren't the only examples throughout where we are left wanting a bit more info.  It might be worth having another scan through to make sure it doesn't come across as a load of bulletpoints.  Refer back to Toma's comments here for a bit more guidance.

- I think the conclusion could really do with a bit more of a summary about the key points addressed in the course.  This is a final sign off, the send away message for the learner, so that they can take away the main issues that you've discussed.
- Citations for the resources mentioned in the 'Further Learning' section would be really helpful here.  I tried looking up that Matt Coeckelbergh book you mentioned, and wasn't really able to find it.  Similarly, a couple of specific examples of the Stanford and MIT projects and articles would be good too.

I'm sorry, I feel bad giving you more work to do here, but I think we are close now!  I'm just going to take the dog for her evening walk now, but I'll check back in when I'm back from our ramble :)

V

**Comment by emilykateemilykate** [comment]
Thank you! I replaced the abstract suggestion and introduced the acronym
AI. As for the table of contents switch- it is toggled :( maybe there's an
issue? but it is toggled!

Happy to do Key Points! And yes, it's Mark :) Mark Coeckelbergh
<https://mitpress.mit.edu/9780262538190/ai-ethics/>.
Coeckelbergh, Mark. *AI Ethics*. The MIT Press, 2020. Happy to add those
citations.

I absolutely get what you mean about fleshing it out further. I'll give it
my best shot to read through it again and add in/take away where it might
pose an issue.

Enjoy the walk and speak soon!
Emily Kate

**Comment by emilykateemilykate** [comment]
Alrighty! I think we're ready for a look!

**Pull request merged**
