### PR TITLE
content(cms): create Resource "processing-ancient-corpora-with-text-fabric/index"

### PR DESCRIPTION
**Pull request by dirkroorda**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by dirkroorda** [comment]
Any indication about when this will get reviewed?

**Comment by VickyGarnett** [comment]
Hi Dirk,

Thanks for getting in touch and making a contribution.  Have you spoken to anyone from the DARIAH-Campus team prior to submitting this contribution?  Did you submit a proposal and have it approved?  I notice on the preview that you put your name as an author at the bottom and then left a note to say that you couldn't find it in the dropdown menu.  Authors are usually added as the result of proposals being submitted.  I'm happy to talk with you more about this proposed resource and the process if you like :) - Vicky

**Comment by dirkroorda** [comment]
Hi Vicky,

indeed, I have not yet spoken to anyone of the DARIAH-Campus team, and that explains why i could not get my name in.
There are two reasons why I submitted:

1. more or less by accident I came across DARIAH-Campus and I am (positively) intrigued by the underlying technology. For an other project I im interested in a git-based authoring environment with a static page generator.
2. I have written Text-Fabric, a tool for processing text corpora, intended for the researcher that has familiarity with coding, albeit just a beginner's course in Python. Since it is a fairly different approach to text-processing than what is currently taught in digital humanities courses, I think it should be taught. 

I have a big family of corpus-specific tutorials (Jupyter Notebooks), and my first go would be to point at these tutorials.
A second move could be to write a textbook that refers to these tutorials.
Alternatively, I could ask key users of text-fabric if they are interested to write *primers* for their students/colleagues/team mates. A primer is a collection of notebooks that shows how text-fabric can be used to address real research questions around a specific corpus.

But, yes, please tell me more about proposals and how to get in.

**Comment by VickyGarnett** [comment]
No problem Dirk, we can get you set up.  I think it would be useful for us to take this conversation off GitHub for the time being, though, so I'll email you directly.  I assume your KNAW email is sufficient?  Thanks - V

**Comment by VickyGarnett** [comment]
Hi @dirkroorda - we haven't had a chance to discuss this resource further.  If you would like to have a chat about it and see how it can fit into DARIAH Campus, then we can arrange a Zoom call.  However, if you no longer wish to proceed with this, I can close this pull request.  If I don't hear from you in 30 days, I'll close the PR in any case.

Thanks :)

Vicky

**Pull request closed without merging**
