### PR TITLE
content(cms): create Resource "introduction-to-programming-for-nlp-with-python/index"

### PR DESCRIPTION
**Pull request by kdesmedt**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi Koenraad @kdesmedt  

Thanks for submitting this.  I think this is promising, but it does need a bit more information to fit our template though.  You can see an example of how we structure the resources here: [https://dariah-campus-7dh56510k-dariah.vercel.app/resource/posts/from-digital-culture-to-digital-heritage](https://dariah-campus-7dh56510k-dariah.vercel.app/resource/posts/from-digital-culture-to-digital-heritage).  

I suspect the bulk of what you've written in the abstract is perhaps best placed in the 'content' field, as this gives more of an insight into what the resource contains.

The abstract itself can then be made considerably shortened to around 50 words, giving a very brief 'taster'.

Finally, we ask for Learning Outcomes where possible.  This allows users to get a good idea of what they can reasonably expect to come away with having completed the course.

If you need it, we do have a step-by-step guide for using the CMS here: [https://campus.dariah.eu/docs/using-the-content-management-system](https://campus.dariah.eu/docs/using-the-content-management-system).  You will be able to make further changes to your resource by going to 'Workflow' and then clicking on the resource in the 'In Review' column.  This will bring you back to the editing page with your resource where you left off with it.  When you start editing and then save your edits, it will move the resource back to your 'drafts' column.  But the same process as before, you can 'save' your edits and then move it from draft back into 'In Review'.

Thanks :)

Vicky

**Comment by kdesmedt** [comment]
I see the desirability of specifying learning outcomes more clearly, but the guide for using the CMS does not clearly suggest where to put these.

**Comment by VickyGarnett** [comment]
No problem, you can simply add them as part of the body text in the 'Content' field.  You can format headings in there if you want to edit using 'Rich Text' or you can toggle to use Markdown if you find that more straightforward. :)

**Comment by kdesmedt** [comment]
Done revising. Stuff reorganized and learning outcomes added.

**Comment by VickyGarnett** [comment]
@stefanprobst or @ttasovac when you have a moment would you be able to take a look at why this branch isn't safe to rebase?  I'd have a go myself but I'd probably make matters worse :). Thanks!  V

**Comment by ttasovac** [comment]
@VickyGarnett you can do a squash and merge instead, it should work.

**Comment by VickyGarnett** [comment]
OK, I've done that.  Has that now sent it for publishing?  Cos it wasn't ready for that yet :\

**Comment by ttasovac** [comment]
Well, yes. But rebase and merge would have published it as well, so I'm not sure what you were trying to do.

**Comment by VickyGarnett** [comment]
Hi Toma - I only wanted to rebase just to update the branch before I made further changes :/. I didn't want to rebase and merge

**Comment by ttasovac** [comment]
hm... how far are you from making final changes? can you do that today and update the published resource? alternatively, you could "revert" the last commit in GitHub Desktop on the main branch —  that should remove the last merged commit, essentially upublishing the post. (if you do that, make sure you copy the resource first, so that you can then commit it manually again in a different branch). the easiest thing, however, would be to finish editing the resources today if you can.

**Comment by ttasovac** [comment]
@stefanprobst just for our education, do you have any advice on unpublishing resources but keeping them for further editing? what would be the best workflow for that?

**Comment by VickyGarnett** [comment]
Yes please @stefanprobst that would be very helpful

**Comment by VickyGarnett** [comment]
@kdesmedt  - could you confirm the date that this resource was first published on your own site?  Even just a month and year, if you can't find the exact date.  This is so that the correct date of first publication can be reflected in the suggested citation.  Otherwise, we'd end up defaulting to the date it was published to Campus.  Thanks :)

**Comment by kdesmedt** [comment]
Hi, the course was first published locally on May 4, 2022.

**Comment by VickyGarnett** [comment]
That's great, thanks Koenraad :)

**Comment by VickyGarnett** [comment]
OK, all published with the correct information now.  When you have a chance @kdesmedt , could you send me a headshot photo that I can add to your profile?  Thanks :)

**Pull request merged**
