### PR TITLE
Ranke2 project

### PR DESCRIPTION
**Pull request by danieleguido**

### CODE REVIEW

**Comment by danieleguido** [comment]
Hi! Do you have any update?

**Comment by ttasovac** [comment]
Hi Daniele. As Vicky wrote to Stef, she couldn't preview your contribution, which usually means that there are some errors in Markdown somewhere. I will have to look at it, but I haven't had time yet. When I do, I will let you know.

**Comment by danieleguido** [comment]
Hi @ttasovac, I don't see any errors running my local clone in dev, but please let me know whether something is missing (probably the build fails?)

**Comment by ttasovac** [comment]
Dear @danieleguido,

neither @VickyGarnett nor myself can commit changes to your pull request. My guess is that when you submitted the pull request, you didn't click on the option "Allow edits from maintainers" —  that option has to be clicked, otherwise we're not given permission to change the pull request, since you're the owner.

Could you please go to the pull request and make this change and let us know here in this thread, once you've done it.

More info on this is here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork 

All best,
Toma

**Comment by danieleguido** [comment]
Hi @ttasovac I can't find the checkbox here as stated on the docs....there's no checkbox available below "notification" area on the right

**Comment by danieleguido** [comment]
I just found this option on our repo settings, can you tell me if it works?
Screenshot 2021-02-16 at 18 52 23

**Comment by danieleguido** [comment]
Otherwise I can just add you both as direct contributors on our fork?

**Comment by ttasovac** [comment]
Yes, please try adding us as collaborators to your fork, that should probably do it.

**Comment by ttasovac** [comment]
thanks, this worked.
@VickyGarnett you should accept the invitation that you get from daniele and then push your local changes again.

**Pull request merged**
