### PR TITLE
content(cms): create Resource "introduction-to-prompt-engineering-in-text-to-text-artificial-intelligence/index"

### PR DESCRIPTION
**Pull request by emilykateemilykate**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - I thought I'd sent a message about this, but it looks like I didn't.

I think this is useful.  I think it could do with a little more information, though.

Before you launch into the 'Methods' section, I think you need a bit of a discussion about what 'Prompt Engineering' is, and what it can be used for in the realm of (digital) humanities.  I think it's also useful to let learners know where they need to go to enter these prompts.  I realise the world of AI is ever changing and a service from OpenAI could disappear in 6 months, but if you can give examples of the kinds of places people go to enter these prompts that would be really useful.

I think it would also be useful to give examples of the outputs from such prompts.

Finally, I think it's useful to discuss what can happen when things go 'wrong' with prompts, and how to rectify them to make sure you get what you're looking for.

I also think it's worth pointing out that, while AI is a powerful tool, it isn't perfect, and the outputs from text generation tools such as ChatGPT require review and necessary revision to make sure they are accurate and meaningful, otherwise you could end up with the text equivalent of a 7-legged dog.  Indeed, adding a section that discusses the cons and as well as the pros of using AI for text or image generation would also be useful. 

To be honest, I'm leaning very much towards suggesting that you combine all these AI prompt tutorials into a single 'Introduction to AI' module, but let's see what these changes I've suggested above can do to make this more of a stand-alone module first.

Thanks! 

V

**Comment by emilykateemilykate** [comment]
Hello @VickyGarnett  ! I hope your summer went well!  I'm just now healing up from a broken arm which has rather slowed me down!  I made the changes you suggested and I combined the AI resources into one. It is in review now for you to take a look at. I focused on introducing what prompt engineering is, where to use it, examples of what it looks like vs a simple prompt, and how one must exercise caution in utilizing the outputs through verification/ corroboration.  Please let me know when we may be able to publish these and if the others are ready (I believe they were and we were going to publish the data and databases and prosopography as curricula?)

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - can I now close this Pull Request if this is part of the combined Intro to AI module?  Thanks :)

**Comment by emilykateemilykate** [comment]
Yes!!

**Pull request closed without merging**
