### PR TITLE
fix: avoid prose styles bleeding into custom mdx components

### PR DESCRIPTION
**Pull request by stefanprobst**
currently, styles for long-form content can bleed into custom mdx components. see e.g. the link text color in the `SideNote` components in [this PR](https://github.com/DARIAH-ERIC/dariah-campus/pull/249).

this avoids that. requires manual check before merge.

### CODE REVIEW

**Comment by ttasovac** [comment]
@stefanprobst I merged this, but, to be honest, I don't quite see the difference. The links in side notes are still black and stand out from the surrounding text. Was that what you were trying to change or something else?

Снимок экрана 2022-02-01 в 07 14 31

**Comment by stefanprobst** [comment]
hmm apparently the typography styles for links are not reset in a `not-prose` block...

**Comment by ttasovac** [comment]
@stefanprobst we also now have this, which I don't think we did before:
Снимок экрана 2022-02-01 в 18 17 22

**Comment by stefanprobst** [comment]
thx, note to self: the `not-prose` opt-out does not get applied to typography overwrites defined in `tailwind.config.js`.

pushed a change which should fix this.

**Pull request merged**
