### PR TITLE
content(cms): create Event "use-of-ict-for-community-building-actions-towards-the-reactivation-of-urban-heritagescapes-in-south-european-cities/index"

### PR DESCRIPTION
**Pull request by Chopium**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
@ttasovac could you authorise the preview for this?  Thanks :)

**Comment by ttasovac** [comment]
Done. It's building now...

**Comment by ttasovac** [comment]
> Error occurred prerendering page "/en/event/use-of-ict-for-community-building-actions-towards-the-reactivation-of-urban-heritagescapes-in-south-european-cities"

**Comment by Chopium** [comment]
Is this build failure something I should be looking into?

**Comment by ttasovac** [comment]
The build failure indicates that something is wrong in the submitted Markdown file. @VickyGarnett can you please look into this?

**Comment by VickyGarnett** [comment]
This is a dumb question, but can I just confirm that you used the CMS to create this resource, and not GitHub directly?  Thanks - V :)

**Comment by Chopium** [comment]
Yes I used the CMS system. There were moments when the preview wouldn't
compile while I was writing but it eventually worked.

**Comment by VickyGarnett** [comment]
OK great, that's useful to know - thanks :)

**Comment by ttasovac** [comment]
Thanks @Chopium and my apologies for the delay. I can't figure out what's wrong here, so I'll have to bring in the heavy artillery :) 

@stefanprobst This is a PR for an event, created in the CMS, @Chopium says it could preview in the CMS, but I can't get it to render either locally or build via Vercel. Could you please take a look?

```
info  - Generating static pages (0/356)
--
14:49:59.192 |  
14:49:59.193 | Error occurred prerendering page "/en/event/use-of-ict-for-community-building-actions-towards-the-reactivation-of-urban-heritagescapes-in-south-european-cities". Read more: https://nextjs.org/docs/messages/prerender-error
14:49:59.193 | Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
14:49:59.195 | at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
14:49:59.196 | at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
14:49:59.196 | at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
14:49:59.196 | at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:596:45)
14:49:59.196 | at Function.getInitialProps (/vercel/path0/.next/server/chunks/6859.js:603:19)
14:49:59.197 | at Object.loadGetInitialProps (/vercel/path0/node_modules/next/dist/shared/lib/utils.js:69:29)
14:49:59.197 | at renderDocument (/vercel/path0/node_modules/next/dist/server/render.js:609:48)
14:49:59.197 | at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:647:34)
14:49:59.197 | at async /vercel/path0/node_modules/next/dist/export/worker.js:273:36
14:49:59.202 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:50:03.959 | info  - Generating static pages (89/356)
14:50:14.050 | info  - Generating static pages (178/356)
14:50:14.749 |  
14:50:14.749 | Error occurred prerendering page "/en/resource/events/use-of-ict-for-community-building-actions-towards-the-reactivation-of-urban-heritagescapes-in-south-european-cities". Read more: https://nextjs.org/docs/messages/prerender-error
14:50:14.754 | Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
14:50:14.754 | at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
14:50:14.754 | at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
14:50:14.754 | at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
14:50:14.755 | at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:596:45)
14:50:14.755 | at Function.getInitialProps (/vercel/path0/.next/server/chunks/6859.js:603:19)
14:50:14.755 | at Object.loadGetInitialProps (/vercel/path0/node_modules/next/dist/shared/lib/utils.js:69:29)
14:50:14.755 | at renderDocument (/vercel/path0/node_modules/next/dist/server/render.js:609:48)
14:50:14.755 | at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:647:34)
14:50:14.755 | at async /vercel/path0/node_modules/next/dist/export/worker.js:273:36
14:50:14.756 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:50:14.975 | info  - Generating static pages (267/356)
14:50:15.697 | info  - Generating static pages (356/356)
14:50:15.708 |  
14:50:15.708 | > Build error occurred
14:50:15.708 | Error: Export encountered errors on following paths:
14:50:15.709 | /en/event/use-of-ict-for-community-building-actions-towards-the-reactivation-of-urban-heritagescapes-in-south-european-cities
14:50:15.709 | /en/resource/events/use-of-ict-for-community-building-actions-towards-the-reactivation-of-urban-heritagescapes-in-south-european-cities
14:50:15.709 | at /vercel/path0/node_modules/next/dist/export/index.js:487:19
14:50:15.709 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
14:50:15.709 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:50:15.709 | at async /vercel/path0/node_modules/next/dist/build/index.js:833:17
14:50:15.710 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:50:15.710 | at async /vercel/path0/node_modules/next/dist/build/index.js:707:13
14:50:15.710 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:50:15.715 | at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:77:25)
14:50:15.775 | error Command failed with exit code 1.
14:50:15.775 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
14:50:15.787 | Error: Command "yarn run build" exited with 1


```

**Comment by VickyGarnett** [comment]
Hi @Chopium  - we've managed to work out the error here, and I've been able to preview it.  I'm more or less ready to publish this, however, I've noticed that in session 5 there is a duplication of the YouTube videos showing up for me.  I'm not sure how this is happening because the information you have provided shows two different links.

In order to go in and fix this, I need the link to the second video: the 'Presentation by Colter Wehmeier'.  I only have the ID for the embed code, and as this video is 'unlisted' I'm unable to find it.  Could you double check that the video hasn't been made private on YouTube as well, just to be on the safe side.

Thanks

Vicky

**Comment by VickyGarnett** [comment]
Hi @Chopium - sorry to bother you, but could you send me to the direct link to the YouTube video for the Presentation by Colter Wehmeier.  It says this video is unlisted, so I can't search for it myself.  This video is causing issues on the research, and I want to try to fix it.  It's the last obstacle to getting this resource published!  Thanks!  V

**Comment by Chopium** [comment]
Thank you for your support in what seems like quite a saga. 
["Developing Wikar AR" by Colter Wehmeier - YouTube](https://www.youtube.com/watch?v=XQfSdYfbdkw)
The id I believe is the hash in the URL!

Colter

**Comment by Chopium** [comment]
Hmm, anything else locking up the site?

**Comment by VickyGarnett** [comment]
Apologies @Chopium, for some reason I didn't get the notice that you had responded with the URL.  As you may be aware, we had our Annual Event from 31 May - 3rd June, which required a lot of preparation in the weeks leading up to it.  In addition I had to take some personal leave last week.  However, now that you've sent me that link, I'll see if I can fix it and get this published for you.

Thanks for your patience :)

V

**Comment by VickyGarnett** [comment]
@ttasovac @stefanprobst I've made that last change now - but it's still showing up with a red cross.  Could you just double-check and make sure there isn't anything there that will go kablooey if I merge this PR?  Thanks :) - V

**Comment by stefanprobst** [comment]
> it's still showing up with a red cross.

every deploy preview from a fork needs to be authorized by toma:

Screenshot_20220615_200752

branch builds fine locally, so LGTM :+1:

**Comment by Chopium** [comment]
Apologies as I was just going over the published page. It looks like the section with Colter Wehmeier and the AR app has the same video linked twice instead of the second video being the lecture. Can this be corrected?
The video link with the caption Presentation by Colter Wehmeier should embed the video below.
https://youtu.be/XQfSdYfbdkw

**Comment by VickyGarnett** [comment]
Hi there - yes, I think this might be the issue I mentioned before somehow cropping up again.  It was working fine when I entered the link you sent me before.  However, I can go back in and fix that now. - V

**Comment by VickyGarnett** [comment]
OK - I've just gone in to make that change, and it's exactly the same link you've sent me that's there for that second video.  However, it seems the link is no longer working, as the preview shows a broken link.  However, I've followed the link myself, and it's working fine.

I've attached a screengrab.  @ttasovac @stefanprobst , do you have any suggestions?  Could it be down to the video being 'unlisted'?

Ta - V

Screenshot 2022-07-06 at 19 49 06

**Comment by Chopium** [comment]
> OK - I've just gone in to make that change, and it's exactly the same link you've sent me that's there for that second video. However, it seems the link is no longer working, as the preview shows a broken link. However, I've followed the link myself, and it's working fine.
> 
> I've attached a screengrab. @ttasovac @stefanprobst , do you have any suggestions? Could it be down to the video being 'unlisted'?
> 
> Ta - V
> 
> Screenshot 2022-07-06 at 19 49 06
Maybe the shortened urls are not compatible with the cms embed. Heres the same url but longer

https://youtube.com/watch?v=XQfSdYfbdkw&

**Comment by Chopium** [comment]
Thank you for your support in what seems like quite a saga.
"Developing Wikar AR" by Colter Wehmeier - YouTube
<https://www.youtube.com/watch?v=XQfSdYfbdkw>
The id I believe is the hash in the URL!

Colter

**Pull request merged**
