### PR TITLE
content(cms): create Resource "everyday-experiences-and-heritage-in-south-european-cities-digital-tools-and-practices/index"

### PR DESCRIPTION
**Pull request by Chopium**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @ttasovac - this doesn't appear to have a preview, do you need to authorise it on Vercel?  Ta!  V :)

**Comment by VickyGarnett** [comment]
Hey @ttasovac have you had a chance to look at the preview issue on this?  Thanks! - V :)

**Comment by ttasovac** [comment]
> Hey @ttasovac have you had a chance to look at the preview issue on this? Thanks! - V :)

I approved the preview and the build completed, you can check out the preview link above.

**Comment by VickyGarnett** [comment]
Hi Chopium,  this appears to be an event, rather than the more traditional resource.  Did you see the instructions for how to put together an event on here?  I'm sorry, I was under the impression this would be a straightforward video, rather than full captured event outputs.  Perhaps we need to have a chat about this, as we have a captured event template that you can use.  Thanks! - V :)

**Comment by Chopium** [comment]
Hmm, let's see the template then.

**Comment by VickyGarnett** [comment]
Cool.  OK, you can see an example of the event format here: https://campus.dariah.eu/resource/events/open-data-citation-for-social-science-and-humanities
If you're using the Content Management System, you can pick up the Event 'Template' by selecting 'Events' in the lefthand menu, and then clicking the 'New Event' button above the list of existing events.  
Full instructions on how to complete the Event template can be found in the documentation, here: https://campus.dariah.eu/docs/using-the-content-management-system#step-23-adding-a-new-event
If you have any questions, give me a shout :)  Ta!  V

**Comment by Chopium** [comment]
I have created a new submission using the event template. 

Please add Dr Alfonso Bahillo Martinez to your list of available contributors so I can add him to the second to last session and finalize.

**Comment by VickyGarnett** [comment]
Hi - I've added Alfonso to the 'People' file now - so you can go ahead and finalise that event.  Thanks :)  V

**Comment by Chopium** [comment]
Thank you! It's all updated and should be ready on my end.

**Comment by VickyGarnett** [comment]
Sorry to ask @Chopium - but is this a separate event to the one that's already published, or a duplicate?  If a duplicate, can we close it?  If it's a different resource, I'll move to publish it.  Ta! - V

**Comment by abstitial** [comment]
This is the same event, we can close it.

**Comment by VickyGarnett** [comment]
Okey-doke - thanks for getting back to me so quickly.  I'll close the PR in that case.  :)

**Pull request closed without merging**
