### PR TITLE
content(cms): create Tag "cultural-heritage"

### PR DESCRIPTION
**Pull request by vdritsou**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @vdritsou - happy to add this, but can you give it a longer description?  Just a short sentence to describe what cultural heritage is.  This then provides the subtitle that you can see at the top of the page under the main tag when you click through from the 'topics' page (see e.g. https://campus.dariah.eu/tag/big-data/page/1)

**Comment by VickyGarnett** [comment]
Hi @vdritsou - I've made a slight modification to your definition, do you want to take a look and make sure you're happy (just click on the commit number to view it) :D

**Comment by vdritsou** [comment]
Commenting here as well (I previously added the same comment under your commit, but I don't know if that's the best place for you to see it) The phrase "to a society or societies" sounds a bit awkward to me. How about "to a community or society" or simply "to a society" instead?

**Comment by VickyGarnett** [comment]
Hi @vdritsou - I've reworked it, see if you're happier now :)

**Comment by vdritsou** [comment]
Hu @VickyGarnett, thank you very much! It's great, I agree

**Comment by VickyGarnett** [comment]
@vdritsou cool, that's merged now.  You should be able to add it to your resource in about 20 mins :)

**Pull request merged**
