### PR TITLE
content(cms): create Resource "data-and-databases-an-introduction/index"

### PR DESCRIPTION
**Pull request by emilykateemilykate**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - finally getting back to looking at these.  I think this first course in the curriculum works well.  However, each course does need to be somewhat standalone.  So I wonder if there can be a little re-wording of the conclusion.  You can see how the ELEXIS curriculum handled this here: https://campus.dariah.eu/resource/posts/introduction-to-dictionaries#instead-of-a-conclusion-where-next

I think it's only a simple case of some light re-wording, perhaps changing 'In this section...' to 'In this short course..', that sort of thing.

Cheers!

V

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - just checking in to see where we are with this?  Have you had a chance to look at the suggestions I gave above?  Thanks!  V

**Comment by emilykateemilykate** [comment]
Will do!! So sorry- got a bit sidetracked but I shall now. Thank you so
much for your thoughtful comments!

**Comment by emilykateemilykate** [comment]
Alright! I took a good look at the suggested ELEXIS curriculum and made the
necessary changes to bring ours up to date! Let me know what you think and
thank you for your patience!

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate  - This is looking great!  I've made a couple of minor changes to the conclusion section so that it makes sense as a 'standalone' resource while also mentioning the curriculum that it will be part of.

Something else to add - you mention that there is an accompanying reading list, but there is no information how to access that.  Can you add a link?  Is this something on Zotero?

Thanks

Vicky

**Comment by VickyGarnett** [comment]
> Hi @emilykateemilykate - This is looking great! I've made a couple of minor changes to the conclusion section so that it makes sense as a 'standalone' resource while also mentioning the curriculum that it will be part of.
> 
> Something else to add - you mention that there is an accompanying reading list, but there is no information how to access that. Can you add a link? Is this something on Zotero?
> 
> Thanks
> 
> Vicky

Hi @emilykateemilykate - just making sure you've seen this, looking for an update re the reading list :). Ta!  V

**Comment by emilykateemilykate** [comment]
Hello! I looked everywhere in my documents from the original source
material and it's nowhere to be found so I removed that sentence
referencing it. Thank you for the reminder!

**Comment by VickyGarnett** [comment]
@emilykateemilykate OK that's great!  Thanks for getting to that so quickly.  In that case, I'll give it one last quick look over and hopefully this one will get published today!

V

**Comment by emilykateemilykate** [comment]
Super news! Thank you!

**Pull request merged**
