### PR TITLE
content(cms): update Person "raapke-annika"

### PR DESCRIPTION
**Pull request by ellisnilsson**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @ellisnilsson - Could you crop this photo so that it's square format.  That way it will fit in the frame we have.  Thanks!  :). V

**Comment by VickyGarnett** [comment]
@ellisnilsson - thanks for updating the photo.  Unfortunately it's telling me that the image isn't valid.  Could you take a look at it and have another go at uploading it?  Thanks!  Vicky

**Comment by VickyGarnett** [comment]
> @ellisnilsson - thanks for updating the photo. Unfortunately it's telling me that the image isn't valid. Could you take a look at it and have another go at uploading it? Thanks! Vicky

Hi @ellisnilsson - as per my comment above - have you had a chance to check that image?  If you can make sure the image is a jpeg or png, is square in format, and approx 200kb max, that would also be helpful.  Also, please avoid any special characters in the filename, and only use the following style for the filename: 'firstname-surname.jpeg'.  Thanks!  

If this problem persists, we might have to try you sending me the image file, and I'll upload it.

V

**Comment by ellisnilsson** [comment]
Hi @VickyGarnett ! Yes, I did that immediately but something seems to be wrong now on my end too when I re-size the image. I'll ask Annika to send a new file.

**Pull request merged**
