### PR TITLE
content(cms): create Person "s-kane-megan"

### PR DESCRIPTION
**Pull request by charlottejmc**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Could you confirm the full name of this person?  What does the 'S' stand for, and is it part of the surname (family name) or this person's middle name?  If it's a middle name, it should go in the 'First Name' field.

**Comment by charlottejmc** [comment]
Hi @VickyGarnett,

Just to confirm, S. is a middle name. Would you be able to make that change for me please? Thanks!

**Comment by VickyGarnett** [comment]
Hi @charlottejmc - I can't make any changes to this because it was your branch and it's been closed.  What we can do as an alternative is create a new branch and do this again.  If you're happy, I can do that for you.  I've checked and this person is not already in the system.  Cheers :). V

**Comment by VickyGarnett** [comment]
> Hi @charlottejmc - I can't make any changes to this because it was your branch and it's been closed. What we can do as an alternative is create a new branch and do this again. If you're happy, I can do that for you. I've checked and this person is not already in the system. Cheers :). V

Scrap that - now that it's reopened I might be able to change it after all.... let me check

**Comment by VickyGarnett** [comment]
@charlottejmc OK I 've think I've done this now.  Please take a look and make sure the 'S' is in the right place :) - V

**Pull request merged**
