### PR TITLE
content(cms): create Resource "prosopography-identity/index"

### PR DESCRIPTION
**Pull request by emilykateemilykate**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by emilykateemilykate** [comment]
I wanted to note that although I formatted these onto the platform and liaised with him throughout the process.  These resources on Prosopography were created by James Baille due to his expertise on the subject and are in his voice.  I want to be sure that he is credited properly according to the platform.  Shall I create a request to add his name as mine was added to the system?  

Thank you for your consideration!

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - I've added James Baille to the system, so you can go back in and add him as an author now.  

For any further authors you should make sure they are listed in your contributions proposals.  If you have additional authors to add, please create a note about it using the reply function in their respective contribution proposals :). I will try to get to them as quickly as I can, although do note I'm travelling for the next two weeks.

**Comment by emilykateemilykate** [comment]
Thank you so much for adding James! I'll be sure to note any others as you suggested. 

I hope you have a beautiful time traveling!

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - I've deployed the previews for each of your resources now, so you should be able to see those previews now.

I've taken a look at this resource, and have some notes for you.

The first is to make sure that you follow the same style as the other hosted resources.  I have recently developed an 'Example of a Hosted Resource' that follows the Campus style guide.   You can view that here: https://dariah-campus-e7r5p2398-dariah.vercel.app/resource/posts/this-is-an-example-of-a-hosted-resource. Please note the Heading hierarchy that is in place, and reformat your current headings accordingly (e.g. 'Learning Outcomes' should be formatted as heading 2).

You also need to add both an introductory section before the learning outcomes that explains roughly what the main topic that you are covering is, and what will be covered within this module.  

You should include a concluding section to review and summarise the main points that have been covered within the module.

Some of this content also feels incomplete and reads a bit too much like bullet-points from a slide.  I think you can tease out some of the topics that a covered a lot more, particularly as 'identity' is such a huge area of research.  I think that more can also be discussed in relation to how prosopography is investigated in digital humanities contexts.

At the end of one of the paragraphs there is the sentence that says 'See below for an example', and yet I don't see an example.

We don't usually peer-review training content, however in this case I would also that some of the content here, particularly in relation to the example given about British identity not being a politically charged statement in the UK, needs some considerably re-working for accuracy.  I can appreciate the author is perhaps coming from an English perspective and therefore British/English is more likely to be used interchangeably (unless you're from Cornwall.  Or Yorkshire.), but Welsh and Scottish people would have a very different opinion.  And furthermore, using the term 'British' as a means of identity in Northern Ireland (part of the UK but not part of Britain) is a VERY political act.  So I think some revision of this section is required.

I think it would also be useful to have some references in this to back up and support what is being laid out as fact here.

These sections on their own feel a little incomplete.  I wonder, therefore if it might make more sense to make one large 'Prosopography' module that draws all these smaller shorter sections together and offers a framework in which they can sit more easily?  We should maybe have a think about might work best here.  However, in the meantime, the comments I have made for this particular module do need to be addressed :)

Thanks

Vicky

**Comment by emilykateemilykate** [comment]
Thank you so much for this thoughtful and detailed feedback!  I'm liaising with James (who is British and I am not) so I will relay to him all of your feedback.  I will address the formatting in accordance with the style guide and see if perhaps it was on my end from his submission that I neglected to include the example.  I think it may have been as for one of the examples, I tried to put the example from one of the drop down formats and then realized it didn't quite fit properly.

Thank you, again for your thoughtful feedback! I'll meet with James and go over it and hopefully we can make the necessary adjustments!

**Comment by emilykateemilykate** [comment]
I have met with James about the  note above and he is reworking the section in question and will submit it to me next week.  I am working on the stylistic and formatting notes myself in the meantime!

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - Sorry for the delay in getting back to you, but I think this Prosopography collection would work best as a single module, much like the AI one.  I'm sorry it's coming so late, but would it be much work now to re-configure it?  Take note of the feedback I gave you for the AI module, and you should be fine :)

**Comment by emilykateemilykate** [comment]
Yes, no problem! Happy to do it today/early tomorrow and send it for your
approval!

**Comment by emilykateemilykate** [comment]
I have completed the prosopography combining and set it for review! Let me
know what you think! :)

**Pull request closed without merging**
