### PR TITLE
content(cms): create Resource "from-the-shelf-to-the-web-exploring-historical-newspapers-in-the-digital-age/index"

### PR DESCRIPTION
**Pull request by spapastamkou**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by spapastamkou** [comment]
Preview looks good, thanks a lot.

**Comment by VickyGarnett** [comment]
Hi @spapastamkou ,

Thanks for this.  I've taken a look, and I've made a minor change to the metadata (the Campus publication date is different from the resource publication date).

I will also make a change to the 'short title' to make it the same as the long title, as it is the title given in the 'short title' field that shows up on the website.

Also, could you add some learning outcomes to this resources.  2-3 are fine.  These are done in bullet points, and finish the sentence "after completing this resource/tutorial, learners will be able to...".  You can see examples of that in the other Ranke2.lu resources, as well as this resource here: https://campus.dariah.eu/resource/posts/curating-the-digital-storytelling-exhibition-at-the-british-library

Thanks!

Vicky

**Comment by spapastamkou** [comment]
Hmm. I see the build fails after my commit - let me know how I can help (and if). I added the learning objectives (and removed a part of the intro to have a more concise text).

**Comment by VickyGarnett** [comment]
@spapastamkou - don't worry too much about the build fail, that usually just means I have to approve the deployment of it.  I've just done that, so it should be viewable as a preview in a few minutes :) - V

**Comment by VickyGarnett** [comment]
Hi @spapastamkou  - so, one major thing I've just noticed is missing is the actual link to the resource!  You should put this after the Learning Outcomes, and use the 'External Resource' option in the drop down menu from the + sign in the CMS :)

There are couple of minor changes I want to make as well, but I will do this after you've added the external link so as not to confuse things :)

V

**Comment by spapastamkou** [comment]
Thank you @VickyGarnett I think it is good now. Also thanks for the changes you have made and please feel free to edit further if necessary. Have a nice day!

**Pull request merged**
