### PR TITLE
chore: Removing CLS Infra duplicate authors

### PR DESCRIPTION
**Pull request by VickyGarnett**
removing duplicate authors created in error for CLS Infra Training School

### CODE REVIEW

**Comment by VickyGarnett** [comment]
@ttasovac Could you take a look at this and see if it makes sense.  I was trying to remove the duplicate authors I created in error.  I need to add authors to the sessions in the CLS-Infra event, and don't want to add the wrong one by mistake!  Thanks :)

**Comment by ttasovac** [comment]
i don't think we'll need this, because i simply won't merge the duplicates that were created by mistake... I#ll come to this soon...

**Comment by ttasovac** [comment]
@VickyGarnett, one thing i don't understand about this commit is why it was necessary to delete [cinkova-silvie.yml](https://github.com/DARIAH-ERIC/dariah-campus/pull/527#diff-230297d81569ddc48597e1c90964eeabc3c2022b61122863958ca3fe4c29b93e)? i get it that those files with numbers are duplicates, but what about this one?

**Comment by VickyGarnett** [comment]
That particular yml doesn't include the special Czech letters that are in Silvie's name, so that one should be removed (the original one included the special characters). :)

**Comment by VickyGarnett** [comment]
Redundant pull request

**Pull request closed without merging**
