### PR TITLE
content(cms): create Resource "introduction-to-applications-of-ai/index"

### PR DESCRIPTION
**Pull request by emilykateemilykate**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by emilykateemilykate** [comment]
If there are any further steps on my end towards publishing, please do remind me! But thank you for your efficiency! I'm sorry I hadn't pushed them to review properly and they sat for so long.  Glad they're on their way!

**Comment by VickyGarnett** [comment]
HI @emilykateemilykate - Thanks for the work on this.  I think it needs a little more work though, unfortunately.  It is very much still a list of bullet-points, and this really needs to be drawn out into more of a prose-like discussion of the applications of AI.  

Also, just a note on formatting, but could you 'toggle on' the 'Table of Contents' option to make that appear.  

Thanks :). V

**Comment by emilykateemilykate** [comment]
The table of contents is toggled :') I wonder why it doesn't show?

I'll try to build out the narrative aspect more here

**Comment by VickyGarnett** [comment]
OK forget the TOC thing - it's on it's just I didn't have the screen zoomed out enough.  That's an 'us' thing to fix, not you :)

**Comment by emilykateemilykate** [comment]
Thank you!

**Comment by emilykateemilykate** [comment]
Alrighty! Reworked it away from bullet points over to a narrative style!!
:)

**Comment by VickyGarnett** [comment]
Hi @emilykateemilykate - just checking, is this also now part of the 'Intro to AI/Prompt Engineering' module?  If so, can I now close this pull request?  Ta!  Just trying to tidy up the list so I know what I need to focus on!

**Comment by emilykateemilykate** [comment]
yes!

**Pull request closed without merging**
