### PR TITLE
content(cms): create Resource "photogrammetry-tutorial/index"

### PR DESCRIPTION
**Pull request by ehanscam**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @ehanscam 

The preview is now available, you can view it by clicking on the 'View Deployment' button above.

There are some changes to be made here, however.

1 - the 'abstract' should be around half the length it currently is.  We recommend around 50-80 word max.  However, you can probably use the current abstract as the description that is also needed in the main content page.
2. I would remove the featured image, as this is misleading and looks like it should be clickable, due to the 'play' button 
3. The format you are going for is an 'External Resource'.  An example of this is here: https://campus.dariah.eu/resource/posts/netnography.  You mentioned that you couldn't add the LNU video link in the 'Video Card' option, this is because it is currently only set up for YouTube, Vimeo, Nakala videos.  Instead, you will need to use the 'External Resource' option to take people to your LNU page.  If you would prefer that this is a 'video card' style resource, then you will need to upload this video to either YouTube, Vimeo or Nakala.  I suspect the same is also true of the other resource you have uploaded.
4. All resources need learning outcomes.  You can also see an example of these in the link above.  You have something similar to that here, but they need pulling out and displaying separately from the main content.  Please follow the format given in the example.

Those are the main changes at this point.  Once you have these in place, we can take a look at any other minor changes (but I suspect you'll probably iron these out along the way with these more significant changes).

Thanks!

Vicky

**Comment by ehanscam** [comment]
hey @VickyGarnett, the view deployment button just shows me the dariah campus homepage..

can you tell me how to get back into the two resources to edit them please? I can't find drafts or anything saved when I go back to the CMS. Thanks!

**Comment by VickyGarnett** [comment]
@ehanscam - I suspect we might need a call to go through these issues.

But, the preview does indeed send you to the Campus home page - you then need to click on 'Resources' at the top of the page, and you will then see your resource 'card' with the abstract.

As for editing your resources once yoou have sent them for review, if you go into the CMS, and then click on 'Workspace' in the top lefthand corner, this will show you your resources in the 'In Review' column.  You can click on these and it will take you back to the editor.

This is all covered in the documentation.  However, as I say I think we might perhaps work more quickly if we can arrange a call to go through this together.  I will email you separately to set up a time.

Thanks :)

**Comment by ehanscam** [comment]
Thanks @VickyGarnett that would probably be a lot easier 😅 can you tell I’m really out of my depth, here?? 😂

I’m away traveling for the next week or so and LNU really wants these posted - how about I try one more time tomorrow with careful use of the guide, and if I’m still clueless we set up a time in mid March when I’m back. Ok?

**Comment by ehanscam** [comment]
@VickyGarnett sorry for the delay, I was away and then ill -- I've edited it to match your example (thanks for that!), let me know if it needs anything else!

**Comment by VickyGarnett** [comment]
Hi @ehanscam - I've made a few edits to the content.  I think this is ready to go now, but it might be a good idea to take a look at the changes I've made, paying particular attention to the formatting and style of the learning outcomes, as it will help you with any more resources you contribute.

Assuming you have no objections to the changes I've made, I'll publish this tomorrow along with the other 'Chroma Key Tutorial" resource (where I made similar changes).

Thanks! 

Vicky

**Comment by ehanscam** [comment]
Hey @VickyGarnett all looks great to me, thank you!

**Pull request merged**
