### PR TITLE
content(cms): create Event "cls-infra-training-school-on-data-and-annotation/index"

### PR DESCRIPTION
**Pull request by VickyGarnett**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hey @ttasovac  - I checked the preview on here, and all the videos are now there, so that's good.  Something I may need some help on next week: the Speakers' Biogs aren't showing up for the individual sessions.  But that's Future Vicky's problem :)

**Comment by VickyGarnett** [comment]
Hi Toma - I've obviously done something to mess this up.  I followed your example in the index.mdx.  The only thing I can think is that there are two fields for speakers for each session now.  Could that be causing a problem?
 - Ta! V

**Comment by ttasovac** [comment]
you have duplicate keys, i.e. the same speaker appearing twice per session. i think that's what's causing the problem please try to fix that (see if there are more examples like the ones in the attached screenshots).

All best,
Toma

On October 10, 2022 at 17:03 GMT, VickyGarnett ***@***.***> wrote:

Hi Toma - I've obviously done something to mess this up. I followed your example in the index.mdx. The only thing I can think is that there are two fields for speakers for each session now. Could that be causing a problem?

- Ta! V

**Comment by ttasovac** [comment]
Also in the yaml file for Maarten you seem to have two descriptions

All best,
Toma

On October 12, 2022 at 12:49 GMT, Toma Tasovac ***@***.***> wrote:

you have duplicate keys, i.e. the same speaker appearing twice per session. i think that's what's causing the problem please try to fix that (see if there are more examples like the ones in the attached screenshots).

All best,
Toma

On October 10, 2022 at 17:03 GMT, VickyGarnett ***@***.***> wrote:

Hi Toma - I've obviously done something to mess this up. I followed your example in the index.mdx. The only thing I can think is that there are two fields for speakers for each session now. Could that be causing a problem?

- Ta! V

**Comment by ttasovac** [comment]
My previous comments look very messy. Sorry about that — i was responding via email and the images seem to have been swallowed. I just got on a plane. Vicky, if my garbled messages make no sense, please ask Stefan if he can help out. I'm traveling the rest of the week so I'm not sure how much I'd be able to help.

**Comment by VickyGarnett** [comment]
haha, no I think I can make it out.  I can't see the images, but the problem seems to be confirmed as I suspected, it's the duplicate speakers that might be causing the issue.  I'll take a look :)

**Comment by ttasovac** [comment]
Hey Vicky, while waiting for another flight :) I noticed that you had a missing `</Speakers>` tag at some point, I just committed it, let's see if that helps.

**Comment by ttasovac** [comment]
Vicky, there was another error —  one pdf file was not correctly named. I fixed it and the site builds now. Check it out here: https://dariah-campus-pztgsv0go-dariah.vercel.app/resource/events/cls-infra-training-school-on-data-and-annotation

**Comment by VickyGarnett** [comment]
Thanks Toma.  Which pdf was it, out of interest.

But, I've forwarded this preview on to the CLS-Infra team, and they are happy with it.  They're getting me some more text to put into that 'About' field, and then I think we are ready to go.

Thanks

V
________________________________

**Comment by ttasovac** [comment]
cool.

2_Maarten-XML-TEI-and-TEITOK.pdf was saved as 2_Maarten-XML-TE-and-TEITOK.pdf or something like that.

**Comment by VickyGarnett** [comment]
@Toma - I've added info to the About field and edited the abstract a bit.  I still had issues building a preview (baffled as to why), so if you get a chance at all, could you give it a quick once over to make sure it's OK.  If it looks good, give me a shout and I'll merge it.  Thx! V

**Comment by ttasovac** [comment]
@VickyGarnett "about" —  just like "prep" is a multiline field. so you have to add two special characters `>-` to indicate that, like here:



Try that and let's see if that's the only thing preventing the build from happening.

**Comment by VickyGarnett** [comment]
Thanks Toma - tried that, and still getting a preview error.  But, I've corrected it in the markdown anyway and pushed that commit, so maybe it helps you?

**Comment by ttasovac** [comment]
Yes, but there must be  another Markdown error, which I can't find. @stefanprobst could you please take a look? This is an event that Vicky had to edit manually because it somehow disappeared from her CMS, we're supposed to publish it tomorrow. Of course, only if you find a moment. Otherwise we'll have to postpone.

**Comment by VickyGarnett** [comment]
Could it be due to the issue regarding French symbols in the TRIPLE posts that keep popping up?  Toma, I've emailed you about that separately :)
________________________________

**Comment by stefanprobst** [comment]
YAML (the format the mdx frontmatter is written in) is whitespace-sensitive, so getting the indentation right is important (it's also why it's no fun to write manually). should be fixed now

**Comment by ttasovac** [comment]
Thanks a lot, Stefan! 🕺 🕺 🕺

**Pull request merged**
