### PR TITLE
content(cms): create Resource "performing-promoting-and-preserving-ireland’s-intangible-cultural-heritage/index"

### PR DESCRIPTION
**Pull request by DEThorpeDRI**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi Debs - I've just gone into  edit this and hopefully merge it, and I see that there isn't actually a video card or video in there.  You should be able to preview this from the link below:

https://dariah-campus-git-fork-dethorpedri-cms-dethorpedr-33c919-dariah.vercel.app/resource/posts/performing-promoting-and-preserving-ireland%E2%80%99s-intangible-cultural-heritage

Do you have the video link for this?  Could you go in and add a Video Card after the learning outcomes for this.  I suggest that rather than have the featured image, you perhaps use that jpeg as the image for the videocard.

Also, if you have images for each of the people listed as authors, could you add them to their profiles?  We prefer to use square format images as these fit better into the template.

Thanks!

Vicky :)

**Comment by VickyGarnett** [comment]
Hi Debs - Have you had a chance to look at this and add that video card?  Alternatively, if you have the link you wanted to add in there, let me know and I can include it.

Thanks

V

**Comment by DEThorpeDRI** [comment]
Hi Vickym

I haven’t, I’m sorry. The training programme is absolutely packed this quarter and I’ve just not had time to get to it.

The link to the video in the Repository is: https://doi.org/10.7486/DRI.9w03fs89x

At some point soon I will put aside some time to adding more videos!

D

**Comment by VickyGarnett** [comment]
No problem, I just wanted to make sure I wasn't leaving it there 🙂
________________________________

**Comment by DEThorpeDRI** [comment]
Hi Vicky,

I wanted to follow up and see if there’s anything I need to do now to publish this?

Apologies to only just be getting to this!

Debs

**Pull request merged**
