### PR TITLE
content(cms): create Resource "automatic-text-recognition-atr-video-1-getting-started/index"

### PR DESCRIPTION
**Pull request by Mareike2405**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @Mareike2405 - This is a big improvement, I think it definitely works best to make the blog post the feature, rather than just the video.

A couple of additional small points to change now: 

1. Tags - I'm not sure e-Heritage is the only tag for this resource, and I'm sure there are others currently available that might suit it better (e.g. 'editing tools').  If you want to make 'Text Recognition' a tag, we can do that as you have several resources to link to it.  However, I would need a very short description from you as to what 'Text Recognition' is.
2. Change the 'Content Type' to "Training Module", as it now has the full module not just the video.
3. The 'Remote URL' needs to be changed to the URL of the blog post, not just the YouTube video
4. You have used 'Part 1' and 'Step1' in the title in two different places.  Either is fine, just pick one and make sure it's consistent :)

I think that's everything for this resource.  If you take a note of these things you can make sure it's the same on the other resources as well.

Thanks :)

Vicky

**Comment by Mareike2405** [comment]
Hi Vicky, great - I am done now with the changes and all should be good!
It would be great to add Automatic Text Recognition as a tag. Here is an explanation: 
Automatic Text Recognition (ATR) refers to the process of acquiring automatically digital textual data from a digitised analog document, usually with machine learning technologies.

**Comment by VickyGarnett** [comment]
Thanks Marieke,

That tag is now published, and you should be able to add it to your resource now.

Thanks

Vicky

**Comment by Mareike2405** [comment]
Thank you very much, Vicky!
I am done with all- good to go. The next step then would be the Curriculum - but I probably have to wait for all the resources to be published?

**Comment by VickyGarnett** [comment]
Yes, when the resources are published we can compile them as a curriculum.

Thanks!

Vicky

**Pull request merged**
