### PR TITLE
content(cms): create Resource "introduction-to-collections-as-data/index"

### PR DESCRIPTION
**Pull request by hibernator11**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi @hibernator11 - this is almost ready to go, but it needs a few edits.  If you can get to these today I might be able to get it published as requested by tomorrow.

1. The abstract needs to be reduced considerably.  It should be no longer than 80 words maximum.
2. Where you have an exercise, please put this into a 'SideNote' and number each exercise so learners know where they are.  Ideally you should also include a heading so that the exercises show up in the Table of Contents on the side.

These should hopefully be quick fixes :)

Thanks

Vicky

**Comment by hibernator11** [comment]
Hi @VickyGarnett,

Thank you very much for your help. I used the interface to include the exercises as sidenotes, I hope it is ok. I reduced the abstract too to 80 words max. Please, let me know if you need anything else from my side.

Best wishes,
Gustavo

**Comment by VickyGarnett** [comment]
Hi @hibernator11 - thanks for making these changes so quickly.  Having seen these changes, some other things are now standing out to me.  

- I think this needs a brief introduction which then leads into the Learning Outcomes before you begin the 'What is the Collections as Data initiative?'.  
- Also, Headings should all have a 'Title Capitalisation' format, so it reads more as "What is the 'Collections as Data' Initiative?".  You should follow this format for all other headings.
- Top headings should start at 'Heading 2' not 'Heading 3'
- You should toggle the 'Show Table of Contents' button in the CMS to 'ON' so that it shows up the module.

Sorry to throw more at you, but it's very nearly there!

Thanks

Vicky

**Comment by VickyGarnett** [comment]
@hibernator11  This is perfect!  Thanks for getting to those changes so promptly!  I'll merge and publish this now, so you should be able to to see it live tomorrow morning and get the link from there :)

V

**Comment by hibernator11** [comment]
Thank you very much @VickyGarnett ! :)

**Pull request merged**
