### PR TITLE
content(cms): create Resource "how-to-capture-and-reference-a-webpage-in-your-research-using-zotero/index"

### PR DESCRIPTION
**Pull request by ClaireB82**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by VickyGarnett** [comment]
@ttasovac @stefanprobst I've looked at the deployment from the Vercel side, and the same error message is coming up for a few of these EHRI resources.  "Error: Command "yarn run build" exited with 1".  It looks like an issue with the preview build, but I can't work out what.  I've had a look at the markdown and it seems fine to me, and I know Claire has been using the CMS to enter information in the metadata fields, so there shouldn't be any room for error there.  What does this message mean, and what can I do to fix it?  Hopefully it's something very easy to resolve anyway.  Thanks!  V

**Comment by stefanprobst** [comment]
thanks for reporting - this is actually a bug caused by non-escaped double quotes in a widget attribute, in this case the `ExternalResource`'s `subtitle`. for now i just removed the quotes, because in other resources we did not quote the resource title in "Check out "The resource title"" either

**Comment by VickyGarnett** [comment]
@stefanprobst Ah ok, that's good to know, because I suggested putting the quote marks in!  I'll remember this for next time, thanks :) V

**Comment by stefanprobst** [comment]
fyi, this is now fixed in the `main` branch

**Comment by VickyGarnett** [comment]
@ClaireB82 Success!  We now have a preview (https://dariah-campus-nv5ztrva1-dariah.vercel.app/resource/posts/how-to-capture-and-reference-a-webpage-in-your-research-using-zotero).  So, please go ahead and finish the rest of those changes, and we can take a look at the preview again before we publish this one.  Thanks!  Vicky

**Comment by VickyGarnett** [comment]
@ClaireB82 I've had a review of the updated resource, and made a few edits.  Could you have a look at the preview (https://dariah-campus-git-fork-claireb82-cms-claireb82dar-158553-dariah.vercel.app/resource/posts/how-to-capture-and-reference-a-webpage-in-your-research-using-zotero) and let me know if you're happy with it.  Once we are all in agreement, I will go ahead and publish it :) - Ta!  V

**Comment by VickyGarnett** [comment]
This has now been merged and published.

**Comment by ClaireB82** [comment]
Hello, 
This is to inform you that I don't have access to the following resource anymore: 
[How to Capture and Reference a Webpage in your Research Using Zotero | DARIAH-Campus (dariah-campus-git-fork-claireb82-cms-claireb82dar-158553-dariah.vercel.app)](https://dariah-campus-git-fork-claireb82-cms-claireb82dar-158553-dariah.vercel.app/resource/posts/how-to-capture-and-reference-a-webpage-in-your-research-using-zotero)
I can’t find it in my workflow overview.. Do you know how I can access it?
With thanks and best wishes, Claire

**Comment by ttasovac** [comment]
This is a published resource. If you want to make changes to it, you need to go to the resource itself on dariah.eu, then click on the link "Suggest changes to resource" which appears at the end of the resource. It will open in the CMS and from there you should be familiar with the interface.

**Comment by ClaireB82** [comment]
Thank you!

**Pull request merged**
