### PR TITLE
fix: remove outlines (showing in safari)

### PR DESCRIPTION
**Pull request by ttasovac**

### CODE REVIEW

**Comment by stefanprobst** [comment]
are these shown when you navigate via mouse or keyboard or always. probably the issue is that safari [does not understand `:focus-visible`](https://caniuse.com/?search=focus-visible). in any case we should not simply remove focus indicators

**Comment by ttasovac** [comment]
@stefanprobst here's the thing. On Safari, when you click anywhere within div.main, you get a blue outline which makes no sense and which doesn't appear on Firefox:

Снимок экрана 2021-08-27 в 11 48 39

This appears on several pages (that I changed with the Tailwind class outline-none). 

One additional thing I just discovered is that on the individual resource pages you don't get the outline when you have a three-column view:

Снимок экрана 2021-08-27 в 11 53 51

but when the outer columns are collapsed, clicking within div.main will produce the unwanted outline:

Снимок экрана 2021-08-27 в 11 51 58

If you can suggest a better way for getting rid of it, please let me know.

**Comment by stefanprobst** [comment]
can you try if  #134 fixes the focus outline around the page content `<main>` in safari?

**Comment by stefanprobst** [comment]
and you also changed the modal dialog - can you post a screenshot of this as well? thanks!

**Comment by ttasovac** [comment]
ah, yes, i forgot about that one. in the modal dialogue, the outline appears when the user clicks outside the input field in Safari, but no Firefox.

Снимок экрана 2021-08-27 в 12 01 56

**Comment by ttasovac** [comment]
yessss #134 fixes the outline in `<main>`

**Comment by stefanprobst** [comment]
cool - i'll hide the modal dialog outline as well, and we can revisit this once safari gets `:focus-visible` support

**Comment by stefanprobst** [comment]
can you check the search dialog please? thx

**Comment by ttasovac** [comment]
yup! thanks a lot stefan. closing my pull request and merging yours.

**Pull request closed without merging**
