### PR TITLE
DARIAH-DE Collection Registry

### PR DESCRIPTION
**Pull request by melina-jander**
Hi, 

As Vicky and I have agreed on, we at CLARIAH-DE submit this External Resource, the DARIAH-DE Collection Registry. Since I am working with GitHub for the first time, I am not sure if I did everything correctly. 

If I need to change something (or start over), please let me know. 

Best wishes
Melina

### CODE REVIEW

**Comment by VickyGarnett** [comment]
Hi Melina,

I promised I'd get in touch.  There are a few missing bits of information that this item needs.  

- The remotePublicationDate  - that is, when was this resource published on the CLARIAH-DE website?

- The abstract needs a bit of re-wording, I'm afraid.  It should not assume any prior knowledge, and should explain why this is a training resource, and not just a link to a tool.  It currently seems to describe two things - both the manual, and the thing that the manual is for, making it a little confusing just what it is that the user is going to find at this resource.  If this is a manual for training people how to use the Collection Registry, then you should explain that from the outset, and then explain what the Collection Registry is.  I wouldn't mention the Publikator tool at all unless it is entirely necessary, as this can also get confusing.  At the moment the abstract seems to talk about how the Collection Registry ISN'T the Publikator, which assumes that people know what the Publikator is (many of them won't).  If they don't need to know what the Publikator is in order to use the Collection Registry, then don't mention the Publikator.  I mentioned before that we hope soon to have a 'curriculum' option that draws related resources together, so at that stage it might be worth looking at that.  But for now, I would avoid mentioning it if you can, as it's a bit confusing.

- The longer description of this resource should also assume no prior knowledge and explain from the outset what this training resource is.  It also requires some 'Learning Outcomes' in order to give the users a better idea why they need to learn about this, and what they'll get out of it.

- Some of the metadata fields are compulsory in order for the item to be published, and for the citation to be generated.  These include the 'date' field, the 'authors' field and the 'remotePublicationDate' field.  Entries that are only partially complete will also not be recognised.  So where you don't know the accurate date, just go with the 1st of the month, or if you only have the year, pick any date in that year.  For the date that the item is published on DARIAH Campus - pick any date in the near future, we can correct this.

- Where you have CLARIAH-DE in the 'contributors' field, that should be moved up to 'Authors'.  In addition, you need to check whether or not they are already listed in the 'person.yaml' file in the 'data' folder.  We try to list these in alphabetical order by surname, but that doesn't mean they all are listed in this way, so you can use control + F (or the Mac equivalent) to find the name you're looking for.  If that person isn't there, you can then enter their name into this file in the same format as the other people listed there.  The 'slug' that you create is what you will put into the 'authors' field in the main index.mdx file.

Speaking of which - I noticed that you had renamed the index.mdx file as 'colreg'.  You should leave this file as 'index.mdx', as this is another one of those complicated file listings.  The content folders that you create require certain files to be there, one of which is 'index.mdx'.  If it's named something else, it won't be found.  

I'm sorry - I know there is a lot here to work on.  GitHub is horribly confusing at the best of times (I still get muddled!), so it's inevitable that fields will get missed!  Do give me a shout if you need me to explain some of this in more detail :)

V

**Comment by melina-jander** [comment]
Hi Vicky,

Your comments are very helfpful – thank you! Familiarising myself with GitHub is quite a learning process, so I appreciate the detailed feedback a lot. ☺

I think I modified all the aspects you mentioned. I tried to use the Publikator entry as an orientation, which is one reason why I did not fill in every metadata field. Another was that I simply did not have some of the information, e.g., the accurate date(s). Your explanations on that are very helpful.
Re-writing the abstract and longer text was the most challenging. I completely agree that without the Publikator as a ‚basis‘, understanding the first versions of the texts is difficult. I still had the idea of the ‚curriculum‘ in mind and within that realm, it seem logical to me to present the Collection Registry as a ‚follow-up‘ on the Publikator. Do the new versions seem more appropriate to you?

It would be great if you‘d have the time to give me another feedback.

Many thanks,
Melina


Von: VickyGarnett ***@***.***>
Gesendet: Dienstag, 25. Mai 2021 18:28
An: DARIAH-ERIC/dariah-campus ***@***.***>
Cc: Jander, Melina ***@***.***>; Author ***@***.***>
Betreff: Re: [DARIAH-ERIC/dariah-campus] DARIAH-DE Collection Registry (#99)


Hi Melina,

I promised I'd get in touch.  There are a few missing bits of information that this item needs.

·        The remotePublicationDate  - that is, when was this resource published on the CLARIAH-DE website?

·        The abstract needs a bit of re-wording, I'm afraid.  It should not assume any prior knowledge, and should explain why this is a training resource, and not just a link to a tool.  It currently seems to describe two things - both the manual, and the thing that the manual is for, making it a little confusing just what it is that the user is going to find at this resource.  If this is a manual for training people how to use the Collection Registry, then you should explain that from the outset, and then explain what the Collection Registry is.  I wouldn't mention the Publikator tool at all unless it is entirely necessary, as this can also get confusing.  At the moment the abstract seems to talk about how the Collection Registry ISN'T the Publikator, which assumes that people know what the Publikator is (many of them won't).  If they don't need to know what the Publikator is in order to use the Collection Registry, then don't mention the Publikator. I mentioned before that we hope soon to have a 'curriculum' option that draws related resources together, so at that stage it might be worth looking at that. But for now, I would avoid mentioning it if you can, as it's a bit confusing.

·        The longer description of this resource should also assume no prior knowledge and explain from the outset what this training resource is.  It also requires some 'Learning Outcomes' in order to give the users a better idea why they need to learn about this, and what they'll get out of it.

·        Some of the metadata fields are compulsory in order for the item to be published, and for the citation to be generated.  These include the 'date' field, the 'authors' field and the 'remotePublicationDate' field.  Entries that are only partially complete will also not be recognised.  So where you don't know the accurate date, just go with the 1st of the month, or if you only have the year, pick any date in that year.  For the date that the item is published on DARIAH Campus - pick any date in the near future, we can correct this.

·        Where you have CLARIAH-DE in the 'contributors' field, that should be moved up to 'Authors'.  In addition, you need to check whether or not they are already listed in the 'person.yaml' file in the 'data' folder.  We try to list these in alphabetical order by surname, but that doesn't mean they all are listed in this way, so you can use control + F (or the Mac equivalent) to find the name you're looking for.  If that person isn't there, you can then enter their name into this file in the same format as the other people listed there.  The 'slug' that you create is what you will put into the 'authors' field in the main index.mdx file.

Speaking of which - I noticed that you had renamed the index.mdx file as 'colreg'.  You should leave this file as 'index.mdx', as this is another one of those complicated file listings.  The content folders that you create require certain files to be there, one of which is 'index.mdx'.  If it's named something else, it won't be found.

I'm sorry - I know there is a lot here to work on.  GitHub is horribly confusing at the best of times (I still get muddled!), so it's inevitable that fields will get missed! Do give me a shout if you need me to explain some of this in more detail :)

V

**Comment by VickyGarnett** [comment]
Hi Melina,

I've had a look at your changes, and made a few more updates.  However, back to the original issue - I'm not sure you did check the box that allows us to make changes to your pull request!  Could you have a look and make sure that is selected.

Thanks!

Vicky

**Comment by VickyGarnett** [comment]
Hi Melina - have you been able to check whether or not the tick-box to 'allow maintainers to contribute' has been selected?  I don't mean to put you under pressure, but we are hoping to get this all published by the weekend as we are planning a system update :) - V

**Comment by melina-jander** [comment]
Hi Vicky, sorry for not replying sooner. Unfortunately, I still cannot check the box that allows you to make changes. I googled it but couldn't find a solution. 
Best wishes, Melina

**Comment by ttasovac** [comment]
Dear Melina, we've encountered this problem in other setups when the forked repository is hosted by an organization rather than an individual. In those cases, the solution is to add @VickyGarnett and myself (@ttasovac) as contributors to your forked DARIAH-Campus repo. That way we can push changes to your pull request before it gets merged.

Vicky is away this week, but she'll be back next week. If you can add us to your repo by Monday, we'll be able to finalize and publish your resource next week.

**Comment by melina-jander** [comment]
Dear Toma, thanks for your reply. As you suggested, I added you and Vicky to my forked DARIAH-Campus repository - I hope it works now. 

Best wishes,
Melina

**Pull request merged**
